### ISSUE TITLE
Use `transfer_keep_alive` as (default) option for transfers

### ISSUE THREAD

**Issue by NukeManDan** [novasamatech/nova-spektr#1024]
## Description

Presently `transfer_allow_death` is the call made with the send button (at least on Polkadot for a TX I tried recently).
I suggest the _default_ call be made to `transfer_keep_alive` : 

https://github.com/paritytech/substrate/blob/0cdf7029017b70b7c83c21a4dc0aa1020e7914f6/frame/balances/src/lib.rs#L625-L632

## Motivation

Help people not footgun that don't know about or understand the existential deposit model.

## Alternatives Considered

Nice to have: a way for power users to select a default, and at tx construction time in the UX override this to what they want.

**Comment by Tbaut** [comment]
Taking this one as I realize that the default is 'allowdeath' which could be surprising for users.
