### ISSUE TITLE
Turn on only Polkadot and Kusama by default

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1412]
When create a Polkadot Vault wallet create main keys only for Polkadot and Kusama by default.

DOD:
1. Only Polkadot and Kusama main keys are created when pairing with Polkadot Vault

**Comment by Tbaut** [comment]
My user feedback if it counts, I think a 1 off check on all the chains should be done upon installation and activate networks that have a balance >0. It would make the UX much better IMHO rather asking users to turn it on themselves.

**Comment by pgolovkin** [comment]
It's a product requirement from stakeholder.

**Comment by Asmadek** [comment]
Suggestion: for dev builds add westend too. It will decrease time for adding accounts, because we mostly use westend during development process

**Comment by stepanLav** [comment]
Status verification: ✅

What has been verified:
- Create new wallet
- Add keys to existing wallet
