### ISSUE TITLE
Enable Matrix SSO login via Google and GitHub

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1413]
Enable Matrix SSO login via Google and GitHub.
Like Element, Cinny does add Google and GitHub login support. The Spektr should check which SSO type is available and show icon for login with Google and/or GitHub.

**Comment by pgolovkin** [comment]
@tuul-wq prototype for SSO login with GitHub or Google https://www.figma.com/proto/XUbuZFQVVRXM5NNGoaB8uq/Gavin's-feedback?page-id=0%3A1&type=design&node-id=24-60022&viewport=502%2C397%2C0.13&t=asZICzJVqOKA9lwk-9&scaling=min-zoom&starting-point-node-id=24%3A60022&show-proto-sidebar=1

**Comment by pgolovkin** [comment]
Button for login [link](https://www.figma.com/file/IzDQl7uzHQVhdnf4tpzXVx/Spektr-Design-System?type=design&node-id=6102-15926&mode=design&t=9MNsVMI6yh7ZJvbE-0)

New icon set [link](https://www.figma.com/file/IzDQl7uzHQVhdnf4tpzXVx/Spektr-Design-System?type=design&node-id=6496-15522&mode=design&t=3Tf3OVWqzpL5BG8r-0)

**Comment by pgolovkin** [comment]
@tuul-wq that's how element handles deeplink https://github.com/element-hq/element-desktop/blob/develop/src/protocol.ts#L97

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Login via GitHub
- Login via Google

Found during testing:
- https://github.com/novasamatech/nova-spektr/issues/1460

**Comment by stepanLav** [comment]
Status verification: ✅
