### ISSUE TITLE
Add "Main" predefined type of key for Derivation Path key generation.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1432]
## Description

Add Main type for "Add keys" flow in Polkadot Vault

**Case:**
1. Add Polkadot Vault wallet
2. Go to Wallet details
3. Click "Edit keys"
4. Try to add  key with type "Main" to Acala

**Expected result:**
User has predefined type "Main" with relaychain spec-name

**Actual result:**
Has not predefined Main DP type
<img width="300" alt="Screenshot 2024-02-08 at 11 08 16" src="https://github.com/novasamatech/nova-spektr/assets/40560660/5a0c4b7b-99df-49af-8a66-33256c580a16">

**Comment by pgolovkin** [comment]
For the `main` key the derivation path should be `specName` from `chains.json` for the selected chain.

**Comment by pgolovkin** [comment]
Also upcoming changes:
1. Main keys will be shown on the edit/view keys screen
2. The user will be able to remove main keys

**Comment by stepanLav** [comment]
Status verification: ✅
