### ISSUE TITLE
Dynamic derivations. Add keys flow. Set focus in failed field when trigger validation error.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1436]
## Description

In add keys flow, user may faced with validation error, it would be great to set user focus in field with error.

## Steps to Reproduce

1. Go to add keys flow for Polkadot Vault
2. Select Polkadot
3. Select Custom key type
4. Click Add new key

## Expected Behavior
When validation error is triggered, user focus go to the field with error (first in order by tab)

## Actual Behavior
User focus stay at Add new key button

https://github.com/novasamatech/nova-spektr/assets/40560660/c85cb998-80f8-42ce-8cc4-73a3f8f87e1b

**Comment by kutu-loncat** [comment]
Halo, I'm a newbie , & not to good about this.
I testify that it was an import error from the database

**Comment by stepanLav** [comment]
Status verification: ✅
