### ISSUE TITLE
[BUG] Proxy worker. Does not create any proxies

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1440]
When user start the app - proxies won't be created.

Log contains only:
`proxy-worker: worker started successfully`
but there is no any messages about accounts and proxies table is empty

Environment:
Have checked on dev(5c6f5f3f39e79bc1a7911c497a27a9d3724a132a) and baseline(1741e33519b51e7b856f4a49498656e6991c57e8) branches

**Comment by pgolovkin** [comment]
[Proxy worker log.log](https://github.com/novasamatech/nova-spektr/files/14239127/Proxy.worker.log.log)

**Comment by stepanLav** [comment]
Status verification: ✅
