### ISSUE TITLE
Create proxy transfers

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1441]
Create proxy operations:
1. Transfers
2. Cross-chain transfers
3. Show validation error if proxy has no funds for network fee

DOD:
1. Implement basic effector model to support multisig & proxy
2. Mix of proxy(mulitisig), multisig(proxy) call should be supported
3. Update confirmation screens according [doc](https://docs.google.com/document/d/1EHcncdvGo4tpA6Gne6ioyjv69H_l48m3DUm8UIKH2WE/edit#heading=h.v4te3y8ejv18)

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Regular transfer
- Cross-chain
- Fee validation
- proxy(mulitisig)
- multisig(proxy)

Found during testing:
- https://github.com/novasamatech/nova-spektr/issues/1641

**Comment by stepanLav** [comment]
Status verification: ✅
