### ISSUE TITLE
Create regular proxy account (delegated authority)

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1442]
Create proxy screen
1. Build list of available proxy accounts 
2. Build list of available proxy type
3. Calculate proxy deposit
4. Validation
5. Confirm create proxy screen
6. Sign operation
7. If transaction executed successfully then save new proxy and update deposit in the database

Doc [link](https://docs.google.com/document/d/1xwzz-geiEvTxIPRPeAh_5R3PENuYjefzE5C-sRtaVtY/edit#heading=h.a2mbaii0vl7e)
Operation confirmation screens [link](https://docs.google.com/document/d/1EHcncdvGo4tpA6Gne6ioyjv69H_l48m3DUm8UIKH2WE/edit#heading=h.e2rr9hgusek3)
Schema with adding the Proxy account for Multisig account on the image below:

![Image](https://github.com/novasamatech/nova-spektr/assets/4741733/82a7ea78-ad6c-4d1b-823c-ebd49f6c05fb)

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Build list of available proxy accounts
- Build list of available proxy type
- Calculate proxy deposit
- Validation
-- can't create proxy for themself 
- Confirm create proxy screen
- save new proxy and update deposit in the database ❌


Found during testing:
- https://github.com/novasamatech/nova-spektr/issues/1611
- https://github.com/novasamatech/nova-spektr/issues/1612
- https://github.com/novasamatech/nova-spektr/issues/1618
- https://github.com/novasamatech/nova-spektr/issues/1614
- https://github.com/novasamatech/nova-spektr/issues/1615
- https://github.com/novasamatech/nova-spektr/issues/1619
- https://github.com/novasamatech/nova-spektr/issues/1620
- https://github.com/novasamatech/nova-spektr/issues/1621
- https://github.com/novasamatech/nova-spektr/issues/1622

**Comment by stepanLav** [comment]
Status verification: ✅
