### ISSUE TITLE
Update Approve, Reject multisig operation Screens

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1443]
1. Approve, reject for transfers with proxy
2. Approve, reject for staking with proxy
3. The account schema is: signatory ➝ multisig ➝ proxied account

Dev comments:
1. Add support of signing multisig operations with proxy (3 sp):
2. Add info about proxied wallet on the confirmation screen

**Comment by pgolovkin** [comment]
@tuul-wq description for multisig proxy operation screens is in the [doc](https://docs.google.com/document/d/1jIiXtQdgGHesdD7Tmr8GcNumF-B9X8OJ7xJgCjAAsh8/edit#heading=h.2v5n0e92n5eg)

**Comment by stepanLav** [comment]
Status verification: ✅

What has been verified:
- Aprove operation
- Reject operation

Found during testing:
https://github.com/novasamatech/nova-spektr/issues/1774
