### ISSUE TITLE
Create proxy staking operations

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1444]
Create proxy operations:
1. Staking operations
2. Show empty screen if delegated to you wallet doesn't have access to the network with staking
3. Show validation error if proxy has no funds for network fee

DOD:
1. Implement basic effector model to support multisig & proxy
2. Mix of proxy(mulitisig), multisig(proxy) call should be supported
3. Update confirmation screens according [doc](https://docs.google.com/document/d/1EHcncdvGo4tpA6Gne6ioyjv69H_l48m3DUm8UIKH2WE/edit#heading=h.v4te3y8ejv18)

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Proxy types
- validation errors


Found during testing:
- https://github.com/novasamatech/nova-spektr/issues/1656
- https://github.com/novasamatech/nova-spektr/issues/1660

**Comment by stepanLav** [comment]
Status verification: ✅
