### ISSUE TITLE
Don't use matrix when all signatories are user's wallets

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1449]
Don't use matrix when all signatories are user's wallets.
1. Don't create matrix room if all signatories are user's wallets
2. Make matrix room id optional
3. Don't send matrix events if matrix room id is empty

**Comment by stepanLav** [comment]
fix:
https://github.com/novasamatech/nova-spektr/pull/1503

**Comment by stepanLav** [comment]
Status verification: ✅
