### ISSUE TITLE
Rewrite creation and removal of custom RPC with FSD + Effector 

### ISSUE THREAD

**Issue by tuul-wq** [novasamatech/nova-spektr#1454]
### Description
In order to increase maintainability and testability of managing custom RPC nodes, we must rewrite that part of code according to FSD with help of `effector`.

What needs to be done:
- [ ] Add new RPC node feature
- [ ] Edit RPC node feature
- [ ] Use `effector-forms` instead of `react-hook-form`
- [ ] Persist existing form validation
- [ ] Tests for add rpc
- [ ] Tests for edit rpc

Reference model: `features/../CurrencyForm` & `features/../CreateContactForm`

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- App fall down when try to add custom node

Can't add custom node:
https://github.com/novasamatech/nova-spektr/assets/40560660/025fbc36-8ab9-4512-83bc-8b579c23feb6

log:
[nova-spektr.log](https://github.com/novasamatech/nova-spektr/files/15072427/nova-spektr.log)

**Comment by pgolovkin** [comment]
@stepanLav fixed with #1719

**Comment by stepanLav** [comment]
Status verification: ✅
