### ISSUE TITLE
The amount of connections isn't equal to the amount of success + connecting + error

### ISSUE THREAD

**Issue by Tbaut** [novasamatech/nova-spektr#1456]
## Description
![image](https://github.com/novasamatech/nova-spektr/assets/33178835/6fbdee0e-59e5-4c3e-8a25-95d09b1bbe39)
An image sums it up. It is weird that the amount of the left isn't equal to the sum of the amounts on the right.
## Steps to Reproduce

1. go to settings>networks
2. see the issue

## Expected Behavior
Have the sum of the numbers on the right equal to the number on the left

## Actual Behavior
They are not equal

## Screenshots
See above

## Possible Solution
I looked into it and realized that we do not take into account the connections with the status `isDisconnectedStatus`. Also in the list we mark them as "Connecting..." which is misleading.

**Comment by pgolovkin** [comment]
Connected to #1455 and may be fixed with it.

**Comment by Tbaut** [comment]
It's somewhat different, as in it's a very specific omission, but it can be addressed in the same PR yes, I discovered it while looking at #1455

**Comment by stepanLav** [comment]
Status verification: ✅
