### ISSUE TITLE
Deep links. Return to app second time will lead to error.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1460]
## Description

When user click on "Open Nova Spektr.app" second time it will lead to log out and show the error.

## Steps to Reproduce

1. Go to matrix log in flow
2. Login via GitHub
3. Open GitHub link again

## Expected Behavior
Show message, something like "You are already logged in"

## Actual Behavior
Log out from matrix and show an error, can't log in again via old browser window

## Environment

- Operating system: macOS
- Version: Stage build -  Nova-Spektr-Stage-1.4.4-3-arm64.dmg

## Screenshots
<img width="300" alt="Screenshot 2024-02-15 at 12 52 24" src="https://github.com/novasamatech/nova-spektr/assets/40560660/17abd400-20d2-48f2-886e-3119c9407f34">

logs:
[nova-spektr.log](https://github.com/novasamatech/nova-spektr/files/14294915/nova-spektr.log)

**Comment by pgolovkin** [comment]
Second click shouldn't lead to un-login.

**Comment by stepanLav** [comment]
Status verification: ✅
