### ISSUE TITLE
Single wallet multisig. Some unexpected wallets is available for multisig creating flow

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1463]
## Description
For single network multisig creating flow is available unexpected wallets:
- Multisig wallet
- Proxy wallet

## Steps to Reproduce

1. Add multisig and proxied wallets in the app
2. Go to create Single network multisig wallet

## Expected Behavior
Can't select WOW, Multisig wallet, Proxied wallet

## Actual Behavior
<img width="600" alt="Screenshot 2024-02-15 at 17 57 11" src="https://github.com/novasamatech/nova-spektr/assets/40560660/b1da5cd5-9f53-45fc-ba5e-f0908bf1da5b">

## Environment
- Operating system: macOS
- Version: Spektr Stage 1.4.4-3

**Comment by stepanLav** [comment]
Status verification: ✅

**Comment by pgolovkin** [comment]
Not relevant after multisig realase.
