### ISSUE TITLE
EVM Chains support

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1477]
1. Update chains.json (update CI)
2. Update Polkadot Vault transaction signing
3. Transfers in Moonbeam, Moonriver
4. Create multisig operations in Moonbeam, Moonriver
5. Check if Multisig address for Moonbeam, Moonriver is correct (compare with extisting multisig)
6. Check that Matrix (SMP) works with Moonbeam, Moonriver multisigs
7. Check if acccount identicon is correct. It should match Polkadot js apps identicon
8. Check if EVM chains work with Dynamic derivations key generator, Dynamic Derivations transactions.
9. For Single Polkadot Vault wallet create accounts for EMV chains if QR code contains ethereum address, for Substrate chains if QR code contains Substrate address.

PR plans:
1. Pairing accounts with EVM chains
2. Signing operations for EVM chains (transfer)

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Adding EVM network to the chains.json
- Sign operation with 
-- NovaWallet
-- WalletConnect
-- PolkadotVault
- Create single chain multisig
- Create multi chain multisig
- Create multisig operations
- Create XCM transfers with EVM wallet
- Create DP for EVM in Polkadot Vault wallet

Found during testing:
- https://github.com/novasamatech/nova-spektr/issues/1534
- https://github.com/novasamatech/nova-spektr/issues/1535
- https://github.com/novasamatech/nova-spektr/issues/1540
- https://github.com/novasamatech/nova-spektr/issues/1549
- https://github.com/novasamatech/nova-spektr/issues/1550
- https://github.com/novasamatech/nova-spektr/issues/1551
- https://github.com/novasamatech/nova-spektr/issues/1558
- https://github.com/novasamatech/nova-spektr/issues/1559
- https://github.com/novasamatech/nova-spektr/issues/1560
- https://github.com/novasamatech/nova-spektr/issues/1561

**Comment by stepanLav** [comment]
Status verification: ✅
