### ISSUE TITLE
Create a pure proxied for my account

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1479]
1. Create a pure proxy screen
2. Create a pure proxy confirm screen
3. Get from `pureCreated` event the pure proxy address
4. Generate name for Delegated to you wallet
5. Create a delegated to you wallet with pure proxy type in the IndexDB. 
6. Update the spinner component adding a link with navigation to a new Delegated to you wallet

DOD:
1. Create a pure proxy from the name of all wallet types except Delegated to you, Watch only
**2. Pure proxy creation from the name of multisig wallet is a part of this task**

Mockups:
1. Pure proxy creation flow [link](https://www.figma.com/file/IVOhwzG9WJyzBkLBFcdYYl/Delegated-authorities-%7C-Milestone-3?type=design&node-id=1004-108656&mode=dev)

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Create flow
- Database update
- Mockups
- ...

Found during testing:
- https://github.com/novasamatech/nova-spektr/issues/1632

**Comment by stepanLav** [comment]
Status verification: ✅
