### ISSUE TITLE
Remove a pure proxy

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1480]
Update the remove proxy procedure.

1. The user clicks to remove proxy account
2. If the user works with the Delegated to you wallet with pure proxy type and removes the last ANY proxy then the warning has to be shown.
3. If the latest ANY proxy is removed from the Deleted to you wallet then the wallet with the Proxy account should be selected by the Nova Spektr.
4. The application shows [confirmation screen](https://docs.google.com/document/d/1EHcncdvGo4tpA6Gne6ioyjv69H_l48m3DUm8UIKH2WE/edit#heading=h.vcheoh7621sm)
5. The user proceeds to signing

Should be developed:
1. Show Warning if removing the last Any proxy for pure proxied
2. New window with warning about removal the last Any pure proxied. Disallow `ctrl (command) + V`.
3. The text for checking should be matched with localised text
4. Remove proxy confirm screen

DOD:
1. Multisig removal is a part of this task
2. Use effector for removal a pure proxy

Mockups [link](https://www.figma.com/file/IVOhwzG9WJyzBkLBFcdYYl/Delegated-authorities-%7C-Milestone-3?type=design&node-id=1168-110593&mode=design&t=zafmbvQdYb2yFdXT-4)

Depends on #1479

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Revoke access

Found during testing:
- https://github.com/novasamatech/nova-spektr/issues/1623
- https://github.com/novasamatech/nova-spektr/issues/1628
- https://github.com/novasamatech/nova-spektr/issues/1631
- https://github.com/novasamatech/nova-spektr/issues/1630
- https://github.com/novasamatech/nova-spektr/issues/1639
- https://github.com/novasamatech/nova-spektr/issues/1640

**Comment by stepanLav** [comment]
Status verification: ✅
