### ISSUE TITLE
Create indexer for checking if proxy is pure or not

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1484]
Create the single chain indexer for 4 chains:Polkadot, Kusama, Moonbeam, Westend with SubQuery that looks for events:
1. `proxy_pureCreated`
2. `proxy_anonymousCreated`
3. check on old runtime versions pure proxy address exists
4. check that other event name doesn't exist

Indexer should save:
1. pure proxy account address (pure address) in account id format

Indexer should be able to check if the account is a pure proxy. Example of the implementation:
1. Get the list of addresses
2. Return the list of addresses that are pure proxies

Query example may be
```
query {
    delegates(filter: {accountId: {in: ["1", "2"]}}) {
    nodes {
      id
    }
  }
}
```

**Comment by pgolovkin** [comment]
Indexer repo https://github.com/novasamatech/subquery-proxy

**Comment by stepanLav** [comment]
Status verification: ✅
