### ISSUE TITLE
Staking page for single chain multisig. Empty pages is shown for unavailable networks.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1508]
## Description
Is shown empty pages for unavailable networks.

## Steps to Reproduce

1. Create Kusama Single chain multisig wallet
2. Go to the Staking page
3. Select Westend network

## Expected Behavior
User be able to understand that staking is available only in one network (show special page for unavailable networks or filter the list of networks, where staking is available)

## Actual Behavior
<img width="1136" alt="Screenshot 2024-02-28 at 08 32 59" src="https://github.com/novasamatech/nova-spektr/assets/40560660/d4b03cd1-5ee8-49aa-aeae-efd98e420b64">

**Comment by pgolovkin** [comment]
will be fixed in terms of [#2075](https://github.com/novasamatech/nova-spektr/issues/2075)
