### ISSUE TITLE
Single chain multisig. Creates account in all chains for invited device

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1520]
## Description
When user receive invitation for single chain multisig - it will be a multichain multisig.

## Steps to Reproduce

1. Create Single chain multisig on device_a
2. REceive an invitation to single multisig on device_b

## Expected Behavior
Both devices has the same Single chain multisig wallet

## Actual Behavior
device_b have got a multichain multisig, instead of single chain multisig

## Environment

- Operating system: macOS
- Version: Stage - 1.5.0-3

## Screenshots
<img width="1022" alt="Screenshot 2024-02-28 at 16 37 09" src="https://github.com/novasamatech/nova-spektr/assets/40560660/c5990471-3419-4819-821a-1f011c87f8c7">

**Comment by pgolovkin** [comment]
Not relevant after #1729
