### ISSUE TITLE
Update metadata portal from Parity repo in order to support nested parachain view

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1526]

**Comment by pgolovkin** [comment]
Data file for testing.

[data.json](https://github.com/novasamatech/nova-spektr/files/14496657/data.json)

**Comment by pgolovkin** [comment]
Latest metadata files 

[latest metadata.zip](https://github.com/novasamatech/nova-spektr/files/14507199/latest.metadata.zip)

**Comment by stepanLav** [comment]
Status verification: ✅

What has been verified:
- Navigation
- Search
- Tab switching
- Spektr interaction
