### ISSUE TITLE
Integrate accounts into wallet inside walletModel

### ISSUE THREAD

**Issue by tuul-wq** [novasamatech/nova-spektr#1529]
Currently we save `wallets` & `accounts` into separate stores in `walletModel`.
But every time we need to get wallet's accounts we iterate over all accounts searching for a match with `walletId`.
Moreover type guards for wallet type doesn't provide appropriate type for wallet's accounts, thus we have to check their type as well which definitely should be unnecessary.

To greatly reduce the amount of work we have to do to map accounts to the specific wallet,
I suggest to map `accounts` into `wallet`.
```javascript
const wallet: Wallet = {
  // wallet properties
  accounts: [ ... ],
};
```

- [ ] update `Wallet` types
- [ ] update `walletModel`
- [ ] update code that relies on wallet & it's accounts
- [ ] update wallet/accounts/permission utils

**Comment by Tbaut** [comment]
This sounds like a great dev experience improvement, and will maybe improve the app's reactivity?

**Comment by tuul-wq** [comment]
> This sounds like a great dev experience improvement, and will maybe improve the app's reactivity?

Most of all it will greatly improve Developer experience and will naturally present how wallets and accounts are connected. Performance will become better indeed.

**Comment by stepanLav** [comment]
Status verification: ✅
