### ISSUE TITLE
Deploy Nova Spektr as webapp

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1541]
Deploy Nova Spektr to github pages. Deploy should be made with CI.

**Stages of development**
MVP:
1. Deploy to the github pages without domain
2. Test and check what is not working
3. Create a CI for deploying from `dev` to the github pages on push

Stage 2:
1. Create 3rd level domain (stage.novaspektr.io) for github pages websited built from `dev` branch

Stage 3:
1. Find a solution for the production web hosting
2. Create 3rd level domain (app.novaspektr.io) 
3. Deploy from `main` branch to the production envirnoment

**Comment by stepanLav** [comment]
Status verification: ✅

What has been verified:
Functions:
- Wallet pairing ✅
- Delete Wallets ✅
- Sign operations ✅
- Multisig operations ✅
- Matrix interaction ✅
-- SSO auth ❌
https://github.com/novasamatech/nova-spektr/issues/1562
- Proxy definition (web workers) ✅
- light clients ✅

UX:
- Camera usage ✅
- Mobile support (resize the window) ❌
https://github.com/novasamatech/nova-spektr/issues/1563
- Redirects from the settings page ✅

Cross browser:
- Safari ✅
https://github.com/novasamatech/nova-spektr/issues/1564
https://github.com/novasamatech/nova-spektr/issues/1565
https://github.com/novasamatech/nova-spektr/issues/1567
- Google chrome ✅
- Firefox ✅
- Edge ✅
- Arc ✅

Additionaly created:
https://github.com/novasamatech/nova-spektr/issues/1566

**Comment by pgolovkin** [comment]
Set the domain name to app.novaspektr.io

**Comment by pgolovkin** [comment]
Dev branch deployment https://spektr-web.s3-website.fr-par.scw.cloud/#/assets
