### ISSUE TITLE
Network list on Settings should be expanded by default

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1544]
Network list on Settings should be expanded by default.

DOD:
1. When the user opens the Networks setting network lists (enabled and disabled) should be expanded by default.
2. When the user makes a search then then network lists should be expanded

**Comment by Tbaut** [comment]
As I said to Yaroslav, I think this is not right. as a user, I would expect disabled networks to be out of the way. I won't die on this hill though.
In any case this is addressed in https://github.com/novasamatech/nova-spektr/pull/1474

**Comment by pgolovkin** [comment]
It was discusses with Yaroslav and design team. Network lists should be expanded by default.

**Comment by Tbaut** [comment]
I read it right, and this doesn't make sense to me :) I give arguments too. Why would users want to have the disabled networks still expanded if they manually disabled them. 

The linked PR does what this issue asks for. As I said, I won't die on this hill, I can agree to disagree, but there is no argument in this issue that tries to convince me why this is good.

**Comment by pgolovkin** [comment]
The approach with expanded list was designed and researched by UX team. It was an original business requirements. UX team is going to create a tech debt in their backlog and make research later.
