### ISSUE TITLE
Add support delivery fee for XCMs

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1552]
Fix on Android for delivery fee:
A message sending chain now can deduct delivery fee. In recent Kusama upgrade exponential delivery fee is introduced calculated using formula:

`F * (B + encoded_msg_len * M)`

where F is a factor that depends on the queue load: dmp.deliveryFactor, xcmpQueue.deliveryFactor

B - base fee constant in xcm config: https://github.com/polkadot-fellows/runtimes/blob/v1.1.0/relay/kusama/src/xcm_config.rs#L116C12-L116C27

M - TransactionByteFee constant in the config: https://github.com/polkadot-fellows/runtimes/blob/v1.1.0/relay/kusama/src/lib.rs#L414

For example, if one is sending KSM: Kusama ➝ Asset Hub. It will now pay:

fee for teleport extrinsic on Kusama
delivery fee on Kusama (by xcm pallet)
xcm execution fee on Asset Hub

Note that xcm-pallet widthraws fee not from the holding but from the sender's balance before sending message to the destination chain.

Android fix PR https://github.com/novasamatech/nova-wallet-android/pull/1411/files

Should be done after ED validation implementation.

**Comment by pgolovkin** [comment]
Part of #2167

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Delivery fee should be added to the Network fee

Expected result:
<img src="https://github.com/user-attachments/assets/f163e617-4d27-4bde-8bd5-8a3105e7e50c" data-canonical-src="https://github.com/user-attachments/assets/f163e617-4d27-4bde-8bd5-8a3105e7e50c" width="300" />

Actual result:
<img src="https://github.com/user-attachments/assets/7ad12605-5c18-44a6-abd7-1c774f711235" data-canonical-src="https://github.com/user-attachments/assets/7ad12605-5c18-44a6-abd7-1c774f711235" width="300"  />

**Comment by stepanLav** [comment]
Status verification: ✅

Additionally found:
https://github.com/novasamatech/nova-spektr/pull/2887
