### ISSUE TITLE
Deploy as a WebApp. Can't properly redirect with SSO auth in matrix.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1562]
## Description
When user try to auth in matrix with GitHub or Google it can't properly redirect.

## Steps to Reproduce

1. Open https://novasamatech.github.io/nova-spektr/
2. Go to Settings
3. Try to Login in Matrix with GitHub

## Expected Behavior
Successful log-in

## Actual Behavior
Wrong redirect

## Environment
- Version: WebApp

**Comment by pgolovkin** [comment]
Fixed after deployment to https://spektr-web.s3-website.fr-par.scw.cloud/#/onboarding
