### ISSUE TITLE
Deploy as WebApp. Has no logic for small screens\mobiles.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1563]
## Description
The Spektr looks wrong for small screens and mobiles

## Steps to Reproduce

1. Open on mobile https://novasamatech.github.io/nova-spektr/

## Expected Behavior
Handdle case when user try to open Spektr with mobile

## Actual Behavior
Wrong UI scale

## Screenshots
![IMG_0C135EEE3E86-1](https://github.com/novasamatech/nova-spektr/assets/40560660/0b30287d-adbf-4542-a8d4-2d829a0e2943)

**Comment by pgolovkin** [comment]
Prepare references from dApps.

**Comment by pgolovkin** [comment]
Polkadot JS Apps

![Image](https://github.com/user-attachments/assets/c43fb58a-e157-4f13-a019-3c2c626198b4)
![Image](https://github.com/user-attachments/assets/c6837cb1-03e8-469a-aec2-0b44478175f4)
![Image](https://github.com/user-attachments/assets/a36664e9-bdc6-40dd-a86c-3d5c72aaafd5)
![Image](https://github.com/user-attachments/assets/11f6a75c-27b9-4ad9-a59f-f53b0dad472d)

**Comment by pgolovkin** [comment]
Multix
![Image](https://github.com/user-attachments/assets/3cdd1c96-0ec7-4da0-9bfc-6a3076049b70)
![Image](https://github.com/user-attachments/assets/2130ce10-d67b-4443-9498-d6e660404669)
![Image](https://github.com/user-attachments/assets/032653d8-251b-4659-8ce2-3dfaf62ecf85)

**Comment by pgolovkin** [comment]
Talisman

![Image](https://github.com/user-attachments/assets/7961ad06-87ad-4a67-bdbc-14f1399090fa)
![Image](https://github.com/user-attachments/assets/0c809e23-a291-41fa-aea8-238b4f3e52fe)

**Comment by pgolovkin** [comment]
Requirements from the design team:
1. when opening Nova Spektr on a mobile phone, the app's width adjusts to the maximum width of the smartphone screen, and the height is set proportionally.
2. we take the minimum app size that we have set and scale it proportionally to the width of the smartphone screen
