### ISSUE TITLE
WebApp. Safari can't play WalletConnect animation properly.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1565]
## Description

Example of animation:

https://github.com/novasamatech/nova-spektr/assets/40560660/653845ec-c8c5-4c99-ba26-f0b594df8599

**Comment by pgolovkin** [comment]
@sokolova-an new video will be provided by November, 22nd.

**Comment by pgolovkin** [comment]
New video https://github.com/user-attachments/assets/74951831-3ee6-497b-9cdd-7a5da8f8fea4

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Safari animation ✅
- Basic animation work ❌

Animation was speeded up.

Expected result:

https://github.com/user-attachments/assets/b86d137b-bcf1-4e20-a390-875ced44598d


Actual result:

https://github.com/user-attachments/assets/6aff88f8-07e9-4668-8696-3bdbe8a4e71b
