### ISSUE TITLE
Try out ".send" instead of ". submitAndWatchExtrinsic"

### ISSUE THREAD

**Issue by tuul-wq** [novasamatech/nova-spektr#1585]
`send` allows to pass a callback, and will give back all the status, events right away, without the need to subscribe

@Tbaut suggested to try `send` - [link](https://github.com/novasamatech/nova-spektr/pull/1547)
Documentation [here](https://polkadot.js.org/docs/api/start/api.tx.subs#transaction-events) & [here](https://polkadot.js.org/docs/api/cookbook/tx#how-do-i-get-the-decoded-enum-for-an-extrinsicfailed-event)

```javascript
.send(sender, ({ status, events }) => {
    if (status.isInBlock || status.isFinalized) {
      events
        // find/filter for failed events
        .filter(({ event }) =>
          api.events.system.ExtrinsicFailed.is(event)
        )
        // we know that data for system.ExtrinsicFailed is
        // (DispatchError, DispatchInfo)
        .forEach(({ event: { data: [error, info] } }) => {
          if (error.isModule) {
            // for module errors, we have the section indexed, lookup
            const decoded = api.registry.findMetaError(error.asModule);
            const { docs, method, section } = decoded;

            console.log(`${section}.${method}: ${docs.join(' ')}`);
          } else {
            // Other, CannotLookup, BadOrigin, no extra info
            console.log(error.toString());
          }
        });
    }
```

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Transfer operations
- Staking operations
- Proxy operations
- Multisig operations


Found during testing:
https://github.com/novasamatech/nova-spektr/issues/1775

**Comment by stepanLav** [comment]
Status verification: ✅
