### ISSUE TITLE
Write service/utils that handles wallet/account acquiring

### ISSUE THREAD

**Issue by tuul-wq** [novasamatech/nova-spektr#1592]
Working with multisigs, signatories and proxied wallets always leads to finding the specific wallet/account which is tedious and obviously repetitive.  We need to come up with a service/utils that abstracts all this away and stops developers from suffering trying to get another signatory for multisig wallet.

Part of this would be solved when we implement #1529 

Most obvious cases:
- Finding wallets for proxied wallet still must be addressed.
- Do not take into account root account for PV wallet.
- Filter WOW when searching through wallets.
- Get wallet by signatory.

**Comment by pgolovkin** [comment]
After DI and plugin approach solution this task is not more relevant.
