### ISSUE TITLE
NetworkSelector should become a part of independent feature

### ISSUE THREAD

**Issue by tuul-wq** [novasamatech/nova-spektr#1594]
Network screen is being decomposed into smaller features, which increases maintainability and testability.
`NetworkSelector` still holds business logic inside UI. When this task is completed `NetworkSelector` should be simple UI dropdown that invokes model's events, calls props for not feature related actions.
There are special conditions for LightClient which are resolved via `ConfirmModal`. They should be also addressed in this task.
Second part requires tinkering with design, I'll be glad to help if needed.

**Manage network feature** should consist of:
- [ ] plain UI `NetworkSelector` (without business logic)
- [ ] stateless `manage-network-model` that only handles connect/disconnect/change events
- [ ] call model's events in UI when trying to connect/disconnect/change
- [ ] Props for actions that do not belong to the feature: `onNewNode`, `onRemoveNode`, `onEditNode`

**Comment by sokolova-an** [comment]
FYI 
Record this issue on the current dev env. Didn't fix it in this task

https://github.com/novasamatech/nova-spektr/assets/63446892/39850fa2-bbdb-412a-a761-a78c97ac91ce

**Comment by stepanLav** [comment]
Status verification: ✅
