### ISSUE TITLE
Run proxy-worker when the user adds, removes the wallet or adds, removes account in the Polkadot Vault wallet

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1604]
Run proxy-worker when the user adds, removes the wallet or adds, removes account in the Polkadot Vault wallet in order to update the list of delegated to you wallets and proxy accounts.

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Add polkadot vault wallet ✅
- Add NovaWallet wallet ✅
- Add multisig wallet ✅
- Add WOW ❌
- Remove wallet ❌
- Create\Delete pure proxy via multisig ✅
