### ISSUE TITLE
Empty delegated authorities tab for new created wallets.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1622]
## Description
When user add new wallet to his Spektr app - delegated authorities tab for this wallet will be empty until restart the app.

## Steps to Reproduce

1. Create wallet with some proxies in polkadot.js
2. Add this wallet to the Spektr
3. Open wallet details
4. Switch to Delegated authorities tab

## Expected Behavior
All delegated authorities is shown for new added wallets

## Actual Behavior
Empty delegated authorities tab

## Environment
https://github.com/novasamatech/nova-spektr/commit/432167ed6b6979d57bd411da75e199bf4d9e501a

## Attachments

<details>
  <summary>Example</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/33666394-a12b-4f57-ae12-82304ea91e0f

</details>

**Comment by pgolovkin** [comment]
Connected with #1604

**Comment by stepanLav** [comment]
Status verification: ✅
