### ISSUE TITLE
Multisig proxy creation. State with error run out of window

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1651]
## Description

<img width="1136" alt="Screenshot 2024-04-09 at 09 31 37" src="https://github.com/novasamatech/nova-spektr/assets/40560660/fd9accb8-53cf-4e69-874d-4a3fdaf80afa">

**Comment by pgolovkin** [comment]
The scroll should be added. Figma [link](https://www.figma.com/file/IVOhwzG9WJyzBkLBFcdYYl/Delegated-authorities-%7C-Milestone-3?type=design&node-id=2277%3A44306&mode=design&t=JUbna8Gn4AMr4Gcj-1).

**Comment by stepanLav** [comment]
Status verification: ✅
