### ISSUE TITLE
Prepare data model for operation basket

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1702]
1. Data model for saving operations
2. Remove operations
3. Mark operation as failed
4. Remove executed operations
5. Validate operation before signing

DOD:
1. Update validation so that it may be reused for signing operations from the Basket screen
2. Update components from the operation list so that it will be possible to reuse them for the Basket
3. Prepare the draw.io data model

**Comment by Asmadek** [comment]
[Data model](https://drive.google.com/file/d/1MylB3hc4p7VPFuTwqE77vfxCwvshJ9EY/view?usp=drive_link)

**Comment by pgolovkin** [comment]
@Asmadek Do `ProxyTxWrapper` and `MultisigTxWrapper` extend `TxWrapper`? 

![Image](https://github.com/novasamatech/nova-spektr/assets/4741733/80be5234-17f0-4757-80b7-40d5277e6682)

**Comment by pgolovkin** [comment]
@Asmadek seems that workflow is not ready but I'll left a comment. 
1. When Tx is submitted and executed then Spektr should remove it from the Basket
2. When Tx failed Spektr should save the error into `Error` object 

![Image](https://github.com/novasamatech/nova-spektr/assets/4741733/ab4862f3-44c5-4db0-96af-159d7e090201)
