### ISSUE TITLE
Update UI lib for portfolio view

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1703]
UI lib mockups https://docs.google.com/document/d/1ktgpK72Ia_xoeqw3cwxA-dAjbxTLWJyWLT_N39afQJo/edit

List of components:
Version 1.3 – 20.03.24
Update component:
1. Amount: changed name from “Amount” to “Assembled amount”, added new component amount;
2. Token: changed name from “Token with amount” to “Token”, added new type “Token with network”;
3. Chain Balance: changed name from “Token balance” to “Chain balance”.
Create component:
1. Amount;
2. Token Balance ✅

**Comment by stepanLav** [comment]
Status verification: ✅
