### ISSUE TITLE
Remove Matrix usage from the application

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1706]
Remove Matrix usage from the application.

- [x] Remove Matrix login
- [x] Remove `MatrixContext` component
- [x] Remove `matrix-sdk` from package.json
- [x] Remove Matrix usage from submit model
- [x] Remove Matrix login from Settings screen
- [x] Check other places where Matrix is being used
- [x] Remove copying `olm.wasm` from webpack config

**Important**: The code should be removed but not commented.

**Comment by Tbaut** [comment]
Thinking about it, and to avoid having a UI that isn't functioning well, we may need to first make sure we retrieve the callData is retrieved from the chain if it's there, and then remove matrix. Should we add it to this todo?

**Comment by pgolovkin** [comment]
Spektr already gets the call data from chain. Spektr gets the information about block number and index of the extrinsic when the multisig transaction was created from chain. After that Nova Spektr gets the extrinsic and checks if callData presented. If callData presents then Spektr saves it.

**Comment by Tbaut** [comment]
ok, if this is already done, then that's great, I'll check it out.

**Comment by Tbaut** [comment]
Note that after this issue is closed, there's an important missing piece which is:
- Multisig discovery based on on-chain data
- The need for a flow for multisig creation with a tx signed by users

These 2 tasks aren't part of the issue right?

**Comment by pgolovkin** [comment]
Right. These 2 tasks aren't part of this issue.
