### ISSUE TITLE
Validator list is not displayed on Kusama

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1707]
Validator list is not displayed on Kusama.

The scenario:
1. Open the Staking page
2. Select nominator
3. Click "Show Validators"

Expected result:
1. The list of selected validator is shown

Actual result:
1. Empty list is shown

Reproduced for start staking, change validators flows.

![Image](https://github.com/novasamatech/nova-spektr/assets/4741733/6afaa804-987f-4894-9c3c-d0eed42c05e7)

**Comment by stepanLav** [comment]
Status verification: ✅

What has been verified:
- Start staking validator list
- Change validators list
- Multisig validators list

Found additionally:
- https://github.com/novasamatech/nova-spektr/issues/1711
