### ISSUE TITLE
Staking. Validator list operates with delays

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1711]
## Description
For the Kusama network validator list operates with delays

<details>
  <summary>🍿 Example 🍿</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/cf9d4248-5463-4b24-8363-feeee31c1a93

</details>

## Steps to Reproduce

1. Go to staking page
2. Initiate start staking \ change validators operation
3. Go to the validator list
4. Try to select validators

## Actual Behavior
UI is lagging, selection process too long

## Environment
https://github.com/novasamatech/nova-spektr/commit/34bc8d02b705548c958d21b2a6fd32d2ecb3a151

**Comment by pgolovkin** [comment]
@tuul-wq please check why Nova Sepktr works slowly when validators are being selected on Kusama. As I see validators selecting doesn't contain any business-logic under the hood.

**Comment by stepanLav** [comment]
Status verification: ✅
