### ISSUE TITLE
Portfolio view. New config with CI

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1721]
1. CI should create file `tokens.json` from `chains.json` and `tokens_dev.json` form `chains_dev.json`
2. JS code for creating `tokens.json` from `chains.json` and `tokens_dev.json` form `chains_dev.json` is located in the task #1415
3. `tokens.json` should group together tokens like `DOT` and `lcDOT` and keep the name of the token for each network. For example `DOT` for Polkadot and `lcDOT` in Acala.

**Comment by sokolova-an** [comment]
updated function:

```
function transformChainstoTokens(chains) {
  const obj = {};
  chains.forEach((i) => {
    i.assets.forEach((asset) => {
      const key = asset.priceId || asset.symbol;
      const updateObj = obj[key] || {
        name: asset.name,
        precision: asset.precision,
        priceId: asset.priceId,
        icon: asset.icon,
        symbol: asset.symbol,
        chains: [],
      };

      obj[key] = {
        ...updateObj,
        chains: [
          ...updateObj.chains,
          {
            chainId: i.chainId,
            name: i.name,
            assetId: asset.assetId,
            assetSymbol: asset.symbol,
            type: asset.type,
            typeExtras: asset.typeExtras,
          },
        ],
      };
    });
  });

  return Object.values(obj);
}
```

**Comment by pgolovkin** [comment]
@stepanLav the result should match [tokens.json](https://github.com/novasamatech/nova-spektr/pull/1744/files#diff-f269a6364327d77f4f836066d25305b93d02c1c6540c5521ea80fdce5953d3b8) file

**Comment by stepanLav** [comment]
Developed in:
https://github.com/novasamatech/nova-spektr-utils/pull/118

**Comment by stepanLav** [comment]
Status verification: ✅
