### ISSUE TITLE
Portfolio view. Create portfolio view

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1722]
1. Toggle for `Chain-centric` and `Token-centric` views
2. Implement `Token-centric` view itself

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Token-centric view
https://github.com/novasamatech/nova-spektr/issues/1834

Found during testing:
- https://github.com/novasamatech/nova-spektr/issues/1844

**Comment by stepanLav** [comment]
Status verification: ✅
