### ISSUE TITLE
Multisig discovery

### ISSUE THREAD

**Issue by Tbaut** [novasamatech/nova-spektr#1741]
As a user, I would like to see all the multisigs that I am a signatory.

follow-up of https://github.com/novasamatech/nova-spektr/pull/1729 and https://github.com/novasamatech/subquery-proxy/pull/6

**Comment by leohar** [comment]
Status verification: ✅ 

What has been verified:
* discover and add ms if at least one signatory added
* add ms wallet if ms is created in app
* discover all ms on different networks
* if add signatories from one ms - ms wallet remains single
* if corresponding signatories are removed then we don't have Reject or Approve buttons
