### ISSUE TITLE
Basket. Save operation to basket

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1746]
Implement Save operation into Basket.

DOD:
1. Add button for saving operation into the Basket if the user makes the operation with `POLKADOT_VAULT` or `MULTISHARD_PARITY_SIGNER` wallet
2. Save operation into the database
3. Save multishard operation as a set of separate single operations
4. Don't forget to create `groupId` for operation(s) when save it

Doc [link](https://docs.google.com/document/d/14j04-R6hvi-LUJq_SSZB6c86YTNAq42jnbB_QyBB09w/edit#heading=h.ihj6hcerke2)
Mockups link **will be later**

**Comment by pgolovkin** [comment]
Under the question: Should Nova Spektr allow to save multisig and proxy operation into the basket.

**Comment by pgolovkin** [comment]
@Asmadek : Nova Spektr doesn't allow to save multisig, proxy operation into the basket (even if it's will be signed with Polkadot Vault)

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Adding to basket flow for `POLKADOT_VAULT`
- Adding to basket flow for `MULTISHARD_PARITY_SIGNER`
- Added to basket message ❌
https://github.com/novasamatech/nova-spektr/issues/1837

Found during testing:
- https://github.com/novasamatech/nova-spektr/issues/1801
-

**Comment by stepanLav** [comment]
All problems were moved to separate issues
