### ISSUE TITLE
Basket. Show operations list

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1747]
Show operation from the database.

DOD:
1. Show operation list from the database
2. Think how to show multisig operations
3. Think how to show proxy operations

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- show all operations type
- operation sorting ❌
https://github.com/novasamatech/nova-spektr/issues/1833
- delete operation
https://github.com/novasamatech/nova-spektr/issues/1848
- select operation
https://github.com/novasamatech/nova-spektr/issues/1847

**Comment by stepanLav** [comment]
All this problems will be implemented in a separate task
