### ISSUE TITLE
Basket. Validate operations

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1748]
Validate operations when open the basket or on refresh button click.

DOD:
1. Show shimmering when loading basket while validation is completed
2. Save validation results into the database
3. Show validation results
4. Run validation on Refresh button click

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Shimmering on page ❌
<details>
  <summary>Shimmering example</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/7b762ca8-cbfa-473c-8715-9bca242747c3

</details>

- Validation state in database ❌

<details>
  <summary>Database data</summary>

![Image](https://github.com/novasamatech/nova-spektr/assets/40560660/68a80dc5-4241-43ae-98c6-17dfdf6dd544)

</details>

- Validation results ❓
-- Some operations consecutive operations should be validated?
-- Validation tooltip
- Refresh button (blocked by - https://github.com/orgs/novasamatech/projects/7/views/13?pane=issue&itemId=64935702)

**Comment by stepanLav** [comment]
Status verification: ✅
