### ISSUE TITLE
Add list of networks with proxy, pure proxy support in spektr-utils

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1759]
1. Add chains where proxy feature is supported into [the list](https://github.com/novasamatech/nova-spektr-utils/tree/main/chains/v1)
2. Add chains where pure proxy feature is supported into [the list](https://github.com/novasamatech/nova-spektr-utils/tree/main/chains/v1)

**Comment by stepanLav** [comment]
https://github.com/novasamatech/nova-spektr-utils/pull/123
