### ISSUE TITLE
Update CI in order to set `multisig` option for Polkadot, Kusama, Moonbeam, Rococo, Westend

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1760]
1. Update repo https://github.com/novasamatech/nova-spektr-utils. Seems that list of multisigs networks should be hard-coded [here](https://github.com/novasamatech/nova-spektr-utils/blob/main/scripts/buildChainsJson.js#L43)
2. Update the [list of chains](https://github.com/novasamatech/nova-spektr-utils/tree/main/chains/v1) where multisig is supported
This should be done right before the release.

**Comment by stepanLav** [comment]
Multisig list has developed in:
https://github.com/novasamatech/nova-spektr-utils/pull/124

**Comment by stepanLav** [comment]
Looks like not actual any more, since we keep other networks for multisig operations

**Comment by pgolovkin** [comment]
The multisig discovery works only in networks with indexers.

**Comment by stepanLav** [comment]
Status verification: ✅
