### ISSUE TITLE
Clean up confirmation screens - check that labels are correct

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1764]
Clean up confirmation screens - check that labels are correct.
For example:
1. `Your wallet` should be changed to `Wallet`
2. `Your account` should be changed `Account`
3. For transfers and cross-chain transfers `Sender` and `Recipient` have to be used

**Comment by stepanLav** [comment]
Status verification: ✅

What has been verified:
- Transfers
- XCM Transfers
- Multisig transfers
- Staking operations
- Proxy operations
