### ISSUE TITLE
Proxy. Confirmation screen missed info about proxy deposit.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1777]
## Description

Confirmation page has no information about proxy deposit:

<img src="https://github.com/novasamatech/nova-spektr/assets/40560660/92d6f675-3c58-4a53-9a1b-128776aeb58b" data-canonical-src="https://github.com/novasamatech/nova-spektr/assets/40560660/92d6f675-3c58-4a53-9a1b-128776aeb58b" width="400" />

<img src="https://github.com/novasamatech/nova-spektr/assets/40560660/e7c7608f-c478-4140-9448-a0776b206ad6" data-canonical-src="https://github.com/novasamatech/nova-spektr/assets/40560660/e7c7608f-c478-4140-9448-a0776b206ad6" width="400" />

Expected result:
https://www.figma.com/design/IVOhwzG9WJyzBkLBFcdYYl/Delegated-authorities-%7C-Milestone-3?node-id=1168-109072&t=bV28DeOsVhQvI1US-4

**Comment by pgolovkin** [comment]
Fixed in 1.11.1 ![Image](https://github.com/user-attachments/assets/34449d9e-f056-463e-bf38-807f604de8e8)
