### ISSUE TITLE
Make Matrix id parameter optional when the user creates contact

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1778]
Since Matrix is no more needed for multisig creation (please check [1756](https://github.com/novasamatech/nova-spektr/issues/1756)), Matrix id parameter in contacts may be optional.

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- migration
- create new contact from the address book
- create new contact from multisig flow

found during testing:
- https://github.com/novasamatech/nova-spektr/issues/1802

**Comment by stepanLav** [comment]
Status verification: ✅
