### ISSUE TITLE
OpenGov. Governance page. Referendums list

### ISSUE THREAD

**Issue by tuul-wq** [novasamatech/nova-spektr#1780]
As a user I want to see list of all referendums.

To do:
- [x] Loading state
- [x] Empty state
- [ ] Sort list by time before approve/reject
- [x] Group list by Ongoing and Completed
- [x] Voted badge
- [x] Referendum title or index when off-chain data not received
- [x] Referendum chart for aye/nay votes (development in separate task)
- [x] Referendum track
- [x] Load off-chain data for each referendum
- [x] Status (Threshold)

[Figma link](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov?node-id=116-13598&t=RafEPHCQCBylgBPp-4)
[Documentation](https://docs.google.com/document/u/1/d/1AWNpTQbmfgLMrILjx1n8UClwPattQ1-6mA3n9Geosms/edit#heading=h.qt3o9jq5owdy)

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Loading state
  - https://github.com/novasamatech/nova-spektr/issues/2002
- Empty state
  - https://github.com/novasamatech/nova-spektr/issues/2004
- Group list
- Voted bage
- Referendum title
- Referendum chart 
- Referendum track
- Load off-chain data ❌
  - https://github.com/novasamatech/nova-spektr/issues/1991
  - https://github.com/novasamatech/nova-spektr/issues/1993
- Status
  - https://github.com/novasamatech/nova-spektr/issues/2010
