### ISSUE TITLE
OpenGov. Governance page. Vote chart

### ISSUE THREAD

**Issue by tuul-wq** [novasamatech/nova-spektr#1781]
As a user I want see vote chart

To do:
- [x] Display aye/nay parts
- [x] Tooltip of votes to pass

Prerequisite for #1780 
[Figma link](https://www.figma.com/design/IzDQl7uzHQVhdnf4tpzXVx/Spektr-Design-System?node-id=7297-14796&t=nW4vbT3yWKwbkHYv-4)

**Comment by stepanLav** [comment]
Status verification: ✅
