### ISSUE TITLE
OpenGov. Governance page. Referendum filter

### ISSUE THREAD

**Issue by tuul-wq** [novasamatech/nova-spektr#1782]
As a user I want to be able to filter referendums by Track and Voted

To do:
- [ ] Track multi-selector
- [ ] Vote selector
- [ ] Clear all button

[Fima link](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov?node-id=100-3233&t=RafEPHCQCBylgBPp-4)

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Problem with update the list after filtering, described here:
https://github.com/novasamatech/nova-spektr/issues/2018
- https://github.com/novasamatech/nova-spektr/issues/2003

**Comment by stepanLav** [comment]
Status verification: ✅
