### ISSUE TITLE
OpenGov. Governance page. Network selector

### ISSUE THREAD

**Issue by tuul-wq** [novasamatech/nova-spektr#1783]
As a user I want to select network of referendums to see

To do:
- [x] Update CI for chains.json in order to show which network supports OpenGov feature
- [x] Network selector
- [x] Send event to request appropriate referendums
- [x] If the user selects the network that is disabled then show screen with link to Network settings

[Figma link](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov?node-id=326-51752&t=RafEPHCQCBylgBPp-4)

**Comment by stepanLav** [comment]
Status verification: ✅

What has been verified:
- Network CI
- Switch between networks
- Disabled network state

Found during testing:
- https://github.com/novasamatech/nova-spektr/issues/1907
