### ISSUE TITLE
OpenGov. Governance page. Locks

### ISSUE THREAD

**Issue by tuul-wq** [novasamatech/nova-spektr#1784]
As a user I want to see my locked tokens

To do:

- [ ] Locked value (for multishard account it must be sum of locks)
- [ ] Unlockable state
- [ ] Loading state
- [ ] Button that leads to "next step"

[Figma link](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov?node-id=326-51756&t=RafEPHCQCBylgBPp-4)
[Figma link to Locked popup](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov-voting?node-id=370-15772&t=fKdMbC3b3otNnBfZ-4)

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Locked value
  - https://github.com/novasamatech/nova-spektr/issues/2061
- Unlockable state
  - https://github.com/novasamatech/nova-spektr/issues/2057
- Loading state

Additionally found:
- https://github.com/novasamatech/nova-spektr/issues/2058
- https://github.com/novasamatech/nova-spektr/issues/2062

**Comment by stepanLav** [comment]
Status verification: ✅
