### ISSUE TITLE
OpenGov. Governance Page. Delegations

### ISSUE THREAD

**Issue by tuul-wq** [novasamatech/nova-spektr#1785]
As a user I want to see my delegated tokens

To do:
- [x] Request delegated tokens `convictionVoting_votingFor`
- [x] Delegated tokens (for multishard value is a sum)
- [x] Loading state
- [x] Button that leads to "next step"

[Figma link](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov?node-id=326-51757&t=RafEPHCQCBylgBPp-4)

**Comment by pgolovkin** [comment]
Example 
```
{
  Delegating: {
    balance: 50,000,000,000,000
    target: 12pXignPnq8sZvPtEsC3RdhDLAscqzFQz97pX2tpiNp3xLqo
    conviction: Locked6x
    delegations: {
      votes: 100,000,000,000
      capital: 100,000,000,000
    }
    prior: [
      18,946,347
      50,000,000,000,000
    ]
  }
}
```
conviction voting для 14AakQ4jAmr2ytcrhfmaiHMpj5F9cR6wK1jRrdfC3N1oTbUz
track - 0

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Delegation amount
  - https://github.com/novasamatech/nova-spektr/issues/2092
- Loading state
  - https://github.com/novasamatech/nova-spektr/issues/2093

**Comment by stepanLav** [comment]
Status verification: ✅
