### ISSUE TITLE
OpenGov. Governance page. Search

### ISSUE THREAD

**Issue by tuul-wq** [novasamatech/nova-spektr#1786]
As a user I want to be able to search through referendums

To do:
- [ ] Search input
- [ ] Filter by index, title

[Figma link](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov?node-id=138-15710&t=RafEPHCQCBylgBPp-4)

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Search by id
https://github.com/novasamatech/nova-spektr/issues/2018
- Search by name
- Switch between Networks
https://github.com/novasamatech/nova-spektr/issues/1905
- Empty results
https://github.com/novasamatech/nova-spektr/issues/1906
- loading state
https://github.com/novasamatech/nova-spektr/issues/2017

**Comment by stepanLav** [comment]
Status verification: ✅
