### ISSUE TITLE
OpenGov. Referendum. Off-chain section

### ISSUE THREAD

**Issue by tuul-wq** [novasamatech/nova-spektr#1787]
As a user I want to see referendum details

To do:
- [x] Modal window with referendum index in header
- [x] Loading state for details
- [x] No data loaded state
- [x] Parsed and properly styled data from the off-chain source

[Figma link](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov?node-id=574-100362&t=RafEPHCQCBylgBPp-4)

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Index in header
- Loading state for details
- Empty state
https://github.com/novasamatech/nova-spektr/issues/2056
- Markdown data parsing
https://github.com/novasamatech/nova-spektr/issues/2055

**Comment by stepanLav** [comment]
Status verification: ✅
