### ISSUE TITLE
OpenGov. Referendum. Votes

### ISSUE THREAD

**Issue by tuul-wq** [novasamatech/nova-spektr#1788]
As a user I want to see my votes

Todo:
- [x] Voted section with total amount of votes
- [x] "My votes" modal window with fragmentation of account/votes/voting power

[Figma link](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov?node-id=574-100471&t=RafEPHCQCBylgBPp-4)
[My votes popup](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov-voting?node-id=273-27249&t=hZlnKtCMb35nXJZl-4)

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- There is no Voted section in Referenda if account has no address for selected chain
https://github.com/novasamatech/nova-spektr/issues/2044
- Voted section layout
https://github.com/novasamatech/nova-spektr/issues/2045
- My votes section
https://github.com/novasamatech/nova-spektr/issues/2046
https://github.com/novasamatech/nova-spektr/issues/2047

**Comment by stepanLav** [comment]
Status verification: ✅
