### ISSUE TITLE
OpenGov. Referendum. Voting status

### ISSUE THREAD

**Issue by tuul-wq** [novasamatech/nova-spektr#1789]
As a user I want to see referendum voting status

Todo:
- [x] Referendum status
- [x] Vote chart
- [x] Threshold
- [x] Actions (vote/revote/retract vote)

[Figma link](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov?node-id=574-100481&t=RafEPHCQCBylgBPp-4)

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Referenda status
- Vote chart
- Threshold
- Update data
https://github.com/novasamatech/nova-spektr/issues/2042

**Comment by stepanLav** [comment]
Status verification: ✅
