### ISSUE TITLE
OpenGov. Referendum. Additional

### ISSUE THREAD

**Issue by tuul-wq** [novasamatech/nova-spektr#1790]
As a user I want to see additional info about referendum.

Todo:
- [x] Additional section with links
- [x] Timeline (from off-chain data source)
- [x] Advanced button
- [x] Advanced modal window with info
- [ ] Show identity for account if it's available

[Fima link](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov?node-id=574-100613&t=RafEPHCQCBylgBPp-4)
[Figma link to timeline](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov-voting?node-id=574-100548&t=hZlnKtCMb35nXJZl-4)
[Figma link to advanced popup](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov-voting?node-id=273-26846&t=hZlnKtCMb35nXJZl-4)

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Additional links ✅
- Timeline
  - https://github.com/novasamatech/nova-spektr/issues/2038
  - https://github.com/novasamatech/nova-spektr/issues/2040
- Advanced
  - https://github.com/novasamatech/nova-spektr/issues/2170

**Comment by stepanLav** [comment]
Status verification: ✅
