### ISSUE TITLE
OpenGov. Referendum. Summary

### ISSUE THREAD

**Issue by tuul-wq** [novasamatech/nova-spektr#1791]
As a user I want to see referendum summary and vote history.

Todo:
- [x] Research how to request data
- [x] Summary of votes
- [x] Vote history modal window
- [x] Search by account
- [x] Show identity for account if it's available

[Figma link](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov?node-id=574-100587&t=RafEPHCQCBylgBPp-4)
[Figma link to history popup](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov-voting?node-id=371-58197&t=hZlnKtCMb35nXJZl-4)

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Identity
https://github.com/novasamatech/nova-spektr/issues/2029
- Search
- Summary data
- Votes sorting
https://github.com/novasamatech/nova-spektr/issues/2031
- Vote History
https://github.com/novasamatech/nova-spektr/issues/2041

Found during testing:
- https://github.com/novasamatech/nova-spektr/issues/2030
- https://github.com/novasamatech/nova-spektr/issues/2037

**Comment by stepanLav** [comment]
Status verification: ✅
