### ISSUE TITLE
Portfolio view. Sorting and filtering

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1792]
Tokens sorting rules:
1. DOT, KSM at the top
2. Production tokens sorted by fiat balance `DESC`
3. Production tokens sorted by balance `DESC` if no fiat balance available
4. Test tokens sorted by balance `DESC`

Chains sorting rules:
1. Polkadot, Kusama at the top
2. Other networks sorted by balance `DESC` if balance is available
3. Other networks sorted by name `DESC`

**Comment by stepanLav** [comment]
Status verification: ✅
