### ISSUE TITLE
Address book. Looks broken without matrixID.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1802]
## Description

without matrixID column, Address Book looks broken:
<img width="300" alt="Screenshot 2024-05-27 at 13 21 08" src="https://github.com/novasamatech/nova-spektr/assets/40560660/b4752e3d-cb46-4b5e-a900-27e6c14da5e1">

**Comment by pgolovkin** [comment]
The second item with matrix ID should be deleted and the first item with account should be a full container.  The size of the row should stay the same.

Example 
![telegram-cloud-photo-size-2-5380109101826168999-y](https://github.com/novasamatech/nova-spektr/assets/4741733/61a6a16b-1ce8-47f1-a7cf-2c6a17c604fb)

**Comment by pgolovkin** [comment]
Figma mockup https://www.figma.com/design/HgFuj8QZd0xqEbkG10DIfs/Flexible-multisig-%7C-Milestone-4?node-id=579-28921&t=BCd4mk3wTxq32YZq-1

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Hover state for edit button too slim



![Image](https://github.com/novasamatech/nova-spektr/assets/40560660/2836caf9-de65-42bb-a3a5-a774b1d0ef86)

**Comment by stepanLav** [comment]
Status verification: ✅
