### ISSUE TITLE
Remove multisig Description and Reject reason

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1807]
Remove multisig description and reject reason.
1. Remove multisig Description on the create multisig operation screen
2. Remove filling Cancel reason when the user rejects multisig operation
3. Remove displaying multisig Description on multisig details screen
4. Remove displaying multisig Cancel reason on multisig details screen

Doc links: 
1. Create and display multisig operation doc https://docs.google.com/document/d/1wWnLwLnu4iddV9O1CJUkZ1ykY56oj18CKaMrI0TytUM/edit#heading=h.vcheoh7621sm
2. Operation confirmation screens doc https://docs.google.com/document/d/1oB7pX_tgBJJD4YI_pSjIwVmSHb7J1la-njYrNPYDmpc/edit#heading=h.vcheoh7621sm

**Comment by Tbaut** [comment]
closed by #2380

**Comment by stepanLav** [comment]
Env:
https://github.com/novasamatech/nova-spektr/commit/7a605cdc3cd1d17d4ff0d9fed736f4090716d795

Status verification: ❌

What has been verified:
- Description on Create Multisig operation removed
<img src="https://github.com/user-attachments/assets/3472e5dc-a84e-4ed3-a08f-0a0dd6248ab1" data-canonical-src="https://github.com/user-attachments/assets/3472e5dc-a84e-4ed3-a08f-0a0dd6248ab1" width="400" />

- Description on confirmation page removed
<img src="https://github.com/user-attachments/assets/ae6d2fe5-7687-4dc6-9df8-baabb745377b" data-canonical-src="https://github.com/user-attachments/assets/ae6d2fe5-7687-4dc6-9df8-baabb745377b" width="400" />

- Description in multisig operations
<img src="https://github.com/user-attachments/assets/9290fdab-1c5a-4220-8ee9-59f6d65ddb4c" data-canonical-src="https://github.com/user-attachments/assets/9290fdab-1c5a-4220-8ee9-59f6d65ddb4c" width="400" />

- Reject reason
<img src="https://github.com/user-attachments/assets/fc799aae-51c8-4485-a4c7-7e56a2503c45" data-canonical-src="https://github.com/user-attachments/assets/fc799aae-51c8-4485-a4c7-7e56a2503c45" width="400" />

**Comment by leohar** [comment]
Status verification: 

What has been verified:

* Description on Create Multisig operation removed


![Image](https://github.com/user-attachments/assets/426d11cc-1429-4fb5-993a-c32a6f677f94)

* Description on confirmation page removed ❌ @Tbaut 
 
![Image](https://github.com/user-attachments/assets/2bf9aaa5-4bb6-445d-a962-a736d112c91b)

* Description in multisig operations

![Image](https://github.com/user-attachments/assets/ae8ab9e9-7467-4da5-b007-4540628a0a11)

* Reject reason

![Image](https://github.com/user-attachments/assets/0f8dd59a-d08b-49e6-a9d3-abfd7559ef53)

**Comment by Tbaut** [comment]
Thanks @leohar I made a PR to remove them all https://github.com/novasamatech/nova-spektr/pull/2520

**Comment by leohar** [comment]
Status verification: ✅
