### ISSUE TITLE
Multisig wallets migration

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1809]
There are 2 types of multisig wallets right now in Nova Spketr:
1. Single chain
2. Multichain

Mutichain wallets won't be present after Matrix removal. So multichain wallet migration should be developed. 

Multichain multisigs.
In Multichain multisigs the `chainId` is `undefined` and the way for migration of such accounts should be defined. 
I see the option to check balance of such multichain multisig wallet balance and create single chain multisig for each network where balance is `greater then 0` and remove old multichain multisig.
It may be done with IndexDB [migration script](https://github.com/novasamatech/nova-spektr/blob/dev/src/renderer/shared/api/storage/migration/index.ts).

**Comment by Tbaut** [comment]
@pgolovkin can you confirm that things are ok with the migration the way I developed the new multisig feature. Older multisigs should still work and this way, we don't need any migration.

**Comment by pgolovkin** [comment]
Old multisigs work well.

**Comment by stepanLav** [comment]
Decided to not migrate
