### ISSUE TITLE
Basket. Confirmation screen for single operation

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1811]
* Show confirm screen for operation when click on it or select only one and sign 
* List of confirm screens 
* Transfer/xcm transfer
* Stacking operations 
* Manage proxy operations

**Comment by stepanLav** [comment]
- https://github.com/novasamatech/nova-spektr/issues/1892
- https://github.com/novasamatech/nova-spektr/issues/1891

**Comment by stepanLav** [comment]
Status verification: ✅
