### ISSUE TITLE
Basket. Show confirmation screen for several operations

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1812]
* Show modal with several operations carousel

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Sign page
https://github.com/novasamatech/nova-spektr/issues/1883
- QR page
https://github.com/novasamatech/nova-spektr/issues/1884

**Comment by stepanLav** [comment]
Status verification: ✅
