### ISSUE TITLE
Basket. Sign operations screen

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1813]
* Sign single operation (usual flow)
* Sign several operations
* Show modal with amount of completed transactions
* Save chain errors for uncompleted transactions
* Remove completed transactions

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Sign regular transfer
- Sign XCM transfer
- Sign staking operations
- Sign Add proxy operation
https://github.com/novasamatech/nova-spektr/issues/1890
- Sign Add pure proxy operation
https://github.com/novasamatech/nova-spektr/issues/1891

**Comment by stepanLav** [comment]
Status verification: ✅
