### ISSUE TITLE
Basket. Filter for transactions

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1814]
* Operation type
* Network
* Operation status

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- UI match
https://github.com/novasamatech/nova-spektr/issues/1957
https://github.com/novasamatech/nova-spektr/issues/1959
- Empty state
https://github.com/novasamatech/nova-spektr/issues/1960
https://github.com/novasamatech/nova-spektr/issues/1958
- Filters logic
https://github.com/novasamatech/nova-spektr/issues/1961

**Comment by stepanLav** [comment]
Status verification: ✅
