### ISSUE TITLE
Basket. Sign button

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1815]
* Operations not selected state
* Operations selected state
* Run valiadetion on click sign
* show modal if some of operations invalid
* Proceed with valid operations only

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Sign transfers
- Sign staking operations
https://github.com/novasamatech/nova-spektr/issues/1896

**Comment by stepanLav** [comment]
Status verification: ✅
