### ISSUE TITLE
Basket. User should not be able to select 'Unavailable' operations.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1847]
## Description
When user has 'Unavailable' operations in his basket - that operations should not be able to select:

<img width="1136" alt="Screenshot 2024-06-06 at 19 42 11" src="https://github.com/novasamatech/nova-spektr/assets/40560660/ff1827c0-2d09-4509-8f27-723738d7313c">

Version:
https://github.com/novasamatech/nova-spektr/commit/1928aa12617eec9261347ffdd8dc1b526f54d590

**Comment by pgolovkin** [comment]
Part of [#1835](https://github.com/novasamatech/nova-spektr/issues/1835)

**Comment by stepanLav** [comment]
Status verification: ✅
