### ISSUE TITLE
Basket. Missed Remove operation confirm dialog.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1848]
## Description
There is no confirm dialog for remove operation from basket

<details>
  <summary>Example</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/5c56f7a1-3fb9-4c8c-b361-a5c888f022d9

</details>

## Steps to Reproduce

1. Add operation to the basket
2. Go to the Basket page
3. Click on remove icon

## Expected Behavior
Show confirmation dialoge

## Actual Behavior
Immediately remove operation

Version:
https://github.com/novasamatech/nova-spektr/commit/1928aa12617eec9261347ffdd8dc1b526f54d590

**Comment by pgolovkin** [comment]
Part of #1810

**Comment by stepanLav** [comment]
Status verification: ✅

Found during testing:
https://github.com/novasamatech/nova-spektr/issues/1912
