### ISSUE TITLE
Basket. Wrong validation state for wallet_mps

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1849]
## Description
For the wallet_mps is available root account, when add transaction to the basket it show unavailable for DED asset.

Account structure:
<img width="496" alt="Screenshot 2024-06-07 at 10 36 26" src="https://github.com/novasamatech/nova-spektr/assets/40560660/b0bec632-f7dd-48e5-b465-9d37bf18803a">

Show unavailable, despite that this account has assets:
<img width="1136" alt="Screenshot 2024-06-07 at 10 37 12" src="https://github.com/novasamatech/nova-spektr/assets/40560660/a64aa52e-044a-412d-9d54-192ba4668821">

DB data:
[accounts.json](https://github.com/user-attachments/files/15721855/accounts.json)
[basketTransactions.json](https://github.com/user-attachments/files/15721856/basketTransactions.json)
[wallets.json](https://github.com/user-attachments/files/15721857/wallets.json)

Version:
https://github.com/novasamatech/nova-spektr/commit/8a195e378cd8e7cfde21a71d509d841d4fb1650a

**Comment by pgolovkin** [comment]
Part of [#1835](https://github.com/novasamatech/nova-spektr/issues/1835)

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Still reproduce



https://github.com/novasamatech/nova-spektr/assets/40560660/c5b29886-180e-4b63-b690-c7b90c59eca8

**Comment by stepanLav** [comment]
Still reproduce the same case with the same data:

![Image](https://github.com/novasamatech/nova-spektr/assets/40560660/cbb3bfce-c227-4c03-a437-41020f84d1cb)

**Comment by stepanLav** [comment]
Status verification: ✅
