### ISSUE TITLE
Token-centric view. Hide zero balances + search works wrong

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1874]
## Description
When user enable `Hide zero balances` feature and try to find any asset where he has 0 balances, search should show that assets.

<details>
  <summary>Example</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/d222d728-96e1-4976-a2d9-6f232af7b490

</details>

## Steps to Reproduce

1. Select account which has any 0 asset (for example ZTG)
2. Enable `Hide zero balances`
3. Enable `Token-centric view`
4. Try to find asset by typing `ztg` into search field

## Expected Behavior
ZTG asset is shown with 0 balances

## Actual Behavior
Nothing to show

## Environment
https://github.com/novasamatech/nova-spektr/commit/496d0a7d8a7261fb5ccf67e4d344cc64a5f7f4aa

**Comment by leohar** [comment]
Status verification: ✅ 

What has been verified:
* view o value tokens in search for 0 value accounts
* view o value tokens in search for have value accounts
* different view: chain/token centric
* regression:  ❌ 
1. hide zero balances is not applied on token-centric view when account has tokens with value on expanded list
https://github.com/user-attachments/assets/ab94bf52-c5f0-47f2-a04b-6201d5c4c236
retested ✅ 
2. if account has 0 AVAIL balance it doesn't appear in search:
https://github.com/user-attachments/assets/6e6ea28f-e002-455a-a091-b0b7663a62dc
would be fixed here: https://github.com/novasamatech/nova-spektr/issues/2354

**Comment by leohar** [comment]
Status verification: ✅ 

retested for 1 and 2 issues
