### ISSUE TITLE
Basket. Can't remove shimmering operations.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1899]
## Description
When user has shimmering operations in his basket - he can't remove it

<details>
  <summary>Example</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/8d2efbb4-03ca-4eda-9d9e-1fe557961e2a

</details>

## Steps to Reproduce

1. Add operations to the basket
2. Make some connection trouble
3. Try to delete operation with shimmering

## Expected Behavior
Can delete operation even if it's shimmering (loading state)

## Actual Behavior
Can't delete that type of operations

## Environment
https://github.com/novasamatech/nova-spektr/commit/399351495f8cedd4b5a0f0de5b8e6c243f521f57

**Comment by pgolovkin** [comment]
Show "small" shimmering instead of "big" shimmering when open the basket.

**Comment by stepanLav** [comment]
Status verification: ✅
