### ISSUE TITLE
UI library. Wrong style for Cancel button

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1912]
## Description

https://www.figma.com/design/BcweKUgqxza0wyIKlxdBu8/Basket?node-id=130-9469&t=79ezdgDALv9HuKUR-4

Cancel button on mockup:
![image](https://github.com/novasamatech/nova-spektr/assets/40560660/20de445a-aec3-491f-9171-9fe0e2afdfaf)

Cancel button in the app:
<img width="500" alt="Screenshot 2024-07-01 at 13 12 34" src="https://github.com/novasamatech/nova-spektr/assets/40560660/3494e598-b6bc-4201-ad1d-336ae8262adf">

**Comment by Tbaut** [comment]
This has been changed in the past and isn't the case any more:


![Image](https://github.com/user-attachments/assets/844abec3-1217-43c1-83c5-52fed80a8575)
