### ISSUE TITLE
OpenGov. Show Governance for the selected wallet accounts

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1919]
Show Governance for the selected wallet accounts

- [ ] Show Governance dashboard for single-shard wallets (WOW, WalletConnect, Single Polkadot vault)
- [ ] Show Governance dashboard multishard wallets (Polkadot Vault, Multishard Polkadot Vault) - votes should be aggregated for all account (shards) from the selected wallet.

**Comment by pgolovkin** [comment]
Check it on `dev` branch

**Comment by stepanLav** [comment]
Status verification: ✅
