### ISSUE TITLE
OpenGov. Governance page. Unlock tokens

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1933]
- [x] Unlock confirm screen for all wallet types. [Figma link](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov-voting?node-id=370-15772&t=hZlnKtCMb35nXJZl-4)
- [x] Multishard confirm screen [Figma link](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov-voting?node-id=733-196219&t=jOASZdpaGlLHp8ZJ-0 )
- [x] Create and sign unlock extrinsic
- [x] Save operation into the basket
- [x] Implement function for basket confirmation screen
- [x] Validation for network fee. Call validation on confirm screen and for basket

**Comment by stepanLav** [comment]
Status verification: ✅
