### ISSUE TITLE
Matrix log-in. Always highlighted tooltip

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1952]
## Description

<img width="600" alt="Screenshot 2024-07-12 at 15 52 03" src="https://github.com/user-attachments/assets/8465448e-f360-4b9f-87e9-448068933345">

## Environment
https://github.com/novasamatech/nova-spektr/commit/af545b88e3986fc20a17e2457da9814e28cf838f

**Comment by pgolovkin** [comment]
Not relevant after Flexible multisig feature implementation.
