### ISSUE TITLE
OpenGov. Delegations. List of delegates

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1971]
* Receive list of delegates from subquery/chain/github **(need more information about it, check ios/android implementation)**
* Show list of delegates
* * Individual
* * Organization
* Search for delegates

**Comment by pgolovkin** [comment]
@Asmadek 
The list of delegations should be retreived from:
1. GitHub Novasama portal https://github.com/novasamatech/opengov-delegate-registry/tree/master
2. From chain

If the user selects the delegator from the list Novasama portal shows an additional long description about the delegator. The list is sorted by delegated amount desc.
Also the Nova Spektr shows the list of delegators that are not in the Novasama portal list but exist on a chain sorted by delegated amount desc..
The user is able to find the delegator by name, blockchain address.
Nova Spektr has to check if the user has delegated tokens for the track when the user votes in order to prevent a failed transaction.

**Comment by stepanLav** [comment]
Status verification: ✅

What has been verified:
- Search for delegate
- Delegates from github
- Delegates from on-chain

Found:
- https://github.com/novasamatech/nova-spektr/issues/2096
