### ISSUE TITLE
OpenGov. Vote. Vote screen

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1979]
OpenGov. Vote. Vote screen

- [x] show About voting popup
- [x] calculate available amount of tokens for voting
- [x] enter the amount of tokens for voting
- [x] enter the conviction (0.1x, 1x, etc)
- [x] show how Governance lock changes
- [x] show locking period
- [x] select Aye/Nay/Abstain
- [x] for Abstain voting show multiplier 0.1x - [mockup](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov-voting?node-id=685-46346&t=NP1elzrHA6b2XQZF-4)
- [x] show network fee

- [x] Validations ([doc](https://docs.google.com/document/d/1AWNpTQbmfgLMrILjx1n8UClwPattQ1-6mA3n9Geosms/edit#heading=h.gwu7jx1ftazg))
- [x] Extrinsics ([doc](https://docs.google.com/document/d/1AWNpTQbmfgLMrILjx1n8UClwPattQ1-6mA3n9Geosms/edit#heading=h.uni5bokpvdu5))

Wallets:
- [x] Single Polkadot Vault wallet
- [x] Proxied wallet
- [ ] WalletConnect, Nova Wallet wallet
- [x] Multishard wallet, Polkadot Vault wallet
- [x] Multisig wallet

[Figma mockups](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov-voting?node-id=652-107673&t=NP1elzrHA6b2XQZF-4)

**Comment by stepanLav** [comment]
Status verification: ✅
