### ISSUE TITLE
OpenGov. Delegations. Add new delegation

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1980]
* Update text for delegation button for empty delegations
* Add new delegation button
* add custom delegate  button
* Step 1 Select tracks
* * Account selector for multishard 
* * Info about different tracks for multishard
* * Check that track isn't voted now, disable it otherwise
* Step 2 Select balance and conviction
* Confirm screen for singleshard
* Confirm screen for multishard
* Update multisig operations
* Update basket operations
* Update proxy operations

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Add custom delegation
  - https://github.com/novasamatech/nova-spektr/issues/2097
  - https://github.com/novasamatech/nova-spektr/issues/2100
  - https://github.com/novasamatech/nova-spektr/issues/2099
  - https://github.com/novasamatech/nova-spektr/issues/2097
- Add new delegation
  - Track page
    - https://github.com/novasamatech/nova-spektr/issues/2117
  - ...
- Remove and add delegation again
  - https://github.com/novasamatech/nova-spektr/issues/2118

**Comment by stepanLav** [comment]
Status verification: ✅
