### ISSUE TITLE
OpenGov. Referendums. Show if the account voted via delegate

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1984]
OpenGov. Referendums. Show if the account voted via delegate

If the user account has delegated votes and the delegate has voted for the referenda then the Voted badge with Delegate info has to be shown on the list of referendas.

The information about delegation should be read from SubQuery.

Figma [mockup](https://www.figma.com/design/4vjREBpvZK7M3m1GaoVptq/OpenGov-delegations?node-id=1-5558&t=0wTTRykyxOWeqxyE-4)

NovaWallet's query to SubQuery:
```js
{
    castingVotings(filter: { voter: {equalTo: "13mAjFVjFDpfa42k2dLdSnUyrSzK8vAySsoudnxX2EKVtfaq"}}) {
        nodes {
            referendumId
            standardVote
            splitVote
            splitAbstainVote
        }
    }

    delegatorVotings(filter: {delegator: {equalTo: "13mAjFVjFDpfa42k2dLdSnUyrSzK8vAySsoudnxX2EKVtfaq"}}) {
        nodes {
            vote
            parent {
                referendumId
                voter
                standardVote
            }
        }
    }
}
```

**Comment by stepanLav** [comment]
Status verification: ✅
