### ISSUE TITLE
OpenGov. Delegations. Sort list of delegates

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#1985]
OpenGov. Delegations. Sort list of delegates

Figma [mockups](https://www.figma.com/design/4vjREBpvZK7M3m1GaoVptq/OpenGov-delegations?node-id=328-112932&t=tNuKSuP8eXBG4Ghf-4)

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Sort by Delegations
- Sort by Delegated votes
  - https://github.com/novasamatech/nova-spektr/issues/2091
- Sort by Voted last 30 days

**Comment by stepanLav** [comment]
Status verification: ✅
