### ISSUE TITLE
OpenGov. Add new unlock form screen

### ISSUE THREAD

**Issue by sokolova-an** [novasamatech/nova-spektr#1995]
- Add new form screens for all types of wallets according to the design [Figma link](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov-voting?node-id=1864-112622&t=3yrMfX6OjAxXj9Q5-0)
- Add validation for the screens

**Comment by stepanLav** [comment]
Status verification: ✅
