### ISSUE TITLE
Error when refresh WalletConnect accounts

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2000]
**Scenario**
1. Open the WalletConnect wallet details
2. Check if the wallet is not connected
3. Try to reconnect

**Expected result**
1. The request is sent to wallet connect
2. After the request approval the wallet is connected
3. The list of accounts is shown

**Actual result**
1. The request is sent to wallet connect
2. After the request approval the error occurs

![Image](https://github.com/user-attachments/assets/4e113c78-74ce-49ff-a3a0-158f74201506)

**Comment by stepanLav** [comment]
Status verification: ✅
