### ISSUE TITLE
Governance. Long loading for accounts with big unlock chunks

### ISSUE THREAD

**Issue by sokolova-an** [novasamatech/nova-spektr#2005]
For accounts with a large amount of lock chunks (more than 900) like (5G7F4oJDMNMxFb1x6N6bJ3LvbNX3uKc7vEzaDbAjGGZUEXFV) loading the script `estimateClaimSchedule` can lead to interface freezing 
The problem happened on the 3d step of the script - `constructUnlockSchedule`

https://github.com/user-attachments/assets/a989b5ca-65ff-4092-b557-545b971eb0fc

**Comment by stepanLav** [comment]
Status verification: ✅
