### ISSUE TITLE
Update account info icon

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2015]
Update info icon for account context menu у account with address and info. The list of components to be updated:
- Item
- Address
- Card signatory
- Root account
- Derived key
- Account
- Account polkadot vault
- Table row
- Wallet
[Design system mockups](https://www.figma.com/design/IzDQl7uzHQVhdnf4tpzXVx/Spektr-Design-System?node-id=6115-11628&t=ppshHdEt8MAWTZwd-1). Подскажите, пожалуйста, сколько времени нужно для этой задачки?

**Comment by stepanLav** [comment]
Status verification: ✅
