### ISSUE TITLE
Governance. Search. Search results are wrong - search by id shows many results.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2018]
## Description
When user try to find referenda by number:
- counter shows numbers, which is not match with the list
- shows too many results, expected only matched by referenda id

## Steps to Reproduce

1. Go to Governance page
2. Enter into search field 33 \ 22 \ 1000

## Expected Behavior
Search filter referenda with entered id

## Actual Behavior
wrong referenda is shown
https://github.com/user-attachments/assets/c1bacea2-447f-48fa-abd7-71606c2fce6a

## Environment
https://github.com/novasamatech/nova-spektr/commit/40e6791613bfe00a5887ff92a9bde304cfb03ccc

**Comment by pgolovkin** [comment]
The search in Nova Wallet works in the same way.

**Comment by stepanLav** [comment]
fixed
