### ISSUE TITLE
PAPI migration

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2019]
PAPI repo https://github.com/polkadot-api/polkadot-api

Definition of done:

- [x] Check if PAPI may be used in Spektr
- [x] Make the demo about PAPI to the team
- [x] Figure out if it's possible to use PAPI and PJS at the same time in the app

**Comment by Tbaut** [comment]
After discussion with the team, I think it's absolutely possible to move to papi.
It is a big refactoring that will require quite deep changes though and it should be though through carefully. 
There is no `api.registry` no `createType` etc. There are strongly typed api per chain and given the amount of chains supported, there needs to be a careful check done.

It is totally possible to use pjs and papi at the same time, but I'd argue it may be difficult in the case of Spektr, given the structure of the app. 

Here's a repo demoing the ability to destructure complex elements with different apis, while keeping the strongly typed nature https://github.com/Tbaut/papi-node/blob/main/src/main.ts

**Comment by Tbaut** [comment]
Hey Pavel, I'm not sure how you want to proceed with this one, but since I'm not well placed to talk about roadmap, I'd mark this as done from my side.

**Comment by pgolovkin** [comment]
Hey @Tbaut. Thanks for onboarding the team to PAPI. Yes, please close the task.
