### ISSUE TITLE
OpenGov. Delegations. Edit delegation

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2024]
* Add edit delegation button on delegate screen if delegated already 
* Edit delegation button on multishard delegation info for single account
* Edit delegation button on multishard delegation info for multiple selected accounts
* Step 1. Select tracks (same as new delegation)
* Step 2. Select balance and conviction (same as new delegation)
* Confirm screen for singleshard
* Confirm screen for multishard
* Update multisig operations
* Update basket operations

**Comment by stepanLav** [comment]
Status verification: ❌

Blocker:
- https://github.com/novasamatech/nova-spektr/issues/2362

**Comment by stepanLav** [comment]
Status verification: ✅
