### ISSUE TITLE
OpenGov. Vote. Multisig list and details

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2025]
OpenGov. Vote. Multisig list and details

- [x] Vote multisig operation list view
- [x] Vote multisig operation detail view
- [x] Decode multisig voting operation
- [x] Approve/Reject screens and signing

The list of attributes is listed in the [doc](https://docs.google.com/document/d/1wWnLwLnu4iddV9O1CJUkZ1ykY56oj18CKaMrI0TytUM/edit#heading=h.4ihnz9amhs17)

[Figma mockups](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov-voting?node-id=688-99422&t=NP1elzrHA6b2XQZF-4)

**Comment by stepanLav** [comment]
Status verification: ✅
