### ISSUE TITLE
OpenGov. Vote. Vote confirmation screen

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2026]
OpenGov. Vote. Vote confirmation screen

Wallets:

- [x]  Single Polkadot Vault wallet
- [ ]  Proxied wallet
- [x]  WalletConnect, Nova Wallet wallet
- [x]  Multishard wallet, Polkadot Vault wallet
- [x]  Multisig wallet
- [ ] Correct governance lock

[Figma mockups](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov-voting?node-id=370-15771&t=NP1elzrHA6b2XQZF-4)

**Comment by stepanLav** [comment]
Status verification: ✅
