### ISSUE TITLE
Splash screen adoption for the web version

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2035]
Nova Spektr JS bundle is 25 MB and it may take about 30 seconds to download it.
During the loading time the splash screen may show different features of the Nova Spektr:
1. Pairing: Polkadot Vault, Nova Wallet, WalletConnect, Multishard account
3. Portfolio: Manage assets, Transfer assets, Cross-chain transfers
4. Staking: On-chain staking
5. Multisigs
6. Proxy: Create proxy and proxy operations
7. OpenGov: Browse referendums, vote and delegate

 
So that the user may be interained and onboarded
![Image](https://github.com/user-attachments/assets/73b2de15-6924-48e8-b47b-1a2c7b8b30ef)

![Image](https://github.com/user-attachments/assets/29b4c962-d254-4bd0-b461-b46a321a1958)

A new splash screen has to be use for the web version only. For the desktop version the current splash screen has to be used. Sabit will provide a splash screen.

**Comment by stepanLav** [comment]
Loading screens:
https://www.figma.com/design/fPddNsaHDaLndvgdVSgS0S/Loading-screens?node-id=88-115&t=SjreBNdCamnrhMIh-1

**Comment by stepanLav** [comment]
Right Image is smaller than on the layouts.
Resolution is the same - 1920x1080

Actual result:

<img width="956" alt="Screenshot 2024-11-26 at 16 13 52" src="https://github.com/user-attachments/assets/014970b1-2f5e-4706-b41b-e9e12e5511c8">


Expected result:
![image](https://github.com/user-attachments/assets/d7098da5-e8f1-4eb6-a1f0-716638006801)

<details>
  <summary>Detailed screens</summary>


<img width="1464" alt="Screenshot 2024-11-26 at 16 22 48" src="https://github.com/user-attachments/assets/21e9aeaf-7a9f-4805-a2db-9291d0fcdedf">
<img width="763" alt="Screenshot 2024-11-26 at 16 23 29" src="https://github.com/user-attachments/assets/15a23f28-2a65-4f31-a8c4-397caa994495">

</details>

**Comment by stepanLav** [comment]
Status verification: ✅
