### ISSUE TITLE
Governance. Vote. Votes status does not update.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2042]
## Description
When user opens Referenda page and someone vote for the referenda (even if it himself) vote status has no changed.

## Steps to Reproduce

1. Go to Governance page
2. Open Referenda
3. Make some votes via another source (polkadot.js)

## Expected Behavior
Votes status has changed in the app

## Actual Behavior
Votes status won't be updated until restart the app

https://github.com/user-attachments/assets/fc3098e6-b557-44d8-98a7-0cd269b1073f

## Environment
https://github.com/novasamatech/nova-spektr/commit/74fb677ee2dd26a02c67eeb6860265cc9bea9add

**Comment by pgolovkin** [comment]
Fixed with #2107

**Comment by stepanLav** [comment]
Status verification: ✅
