### ISSUE TITLE
Governance. Information that current Wallet has no account for selected network.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2044]
## Description

When user go to Governance page with the NovaWallet account or PolkadotVault multishard wallet - there is no information that he has no account for selected chain.

## Steps to Reproduce

1. Select NovaWallet wallet without account for Novasama Testnet - Governance
2. Go to Governance page

## Expected Behavior
Show that the current wallet has no account for selected chain

## Actual Behavior
Does not show any data connected with address

## Environment
https://github.com/novasamatech/nova-spektr/commit/74fb677ee2dd26a02c67eeb6860265cc9bea9add

**Comment by pgolovkin** [comment]
Task for development https://github.com/novasamatech/nova-spektr/issues/2075

**Comment by stepanLav** [comment]
Status verification: ✅

What has been verified:
- WalletConnect
- NovaWallet
- Polkadot Vault
- WOW
