### ISSUE TITLE
Governance. Threshold. Negative value for threshold

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2059]
## Description

Negative value is shown for refereneda threshold
<img width="600" alt="Screenshot 2024-08-09 at 11 45 48" src="https://github.com/user-attachments/assets/dcfa5090-f762-4151-8ffc-1841da82100e">

## Steps to Reproduce

1. Create Origin - Auction Admin referenda on testnet
<img width="400" alt="Screenshot 2024-08-09 at 11 48 36" src="https://github.com/user-attachments/assets/e49a4ea5-07ca-49a2-88a5-e67f44e8a914">

2. Vote for it
3. Waiting until apply

## Expected Behavior
Shouldn't be negative threshold

## Actual Behavior
0.1K of -93264.26407 WND

## Environment
https://github.com/novasamatech/nova-spektr/commit/769e2c447f837eea9cdc8d946a1bd416cacb1fc2

**Comment by Tbaut** [comment]
From my research, the problem seems to come from the return of this `if` block: https://github.com/novasamatech/nova-spektr/blob/bc723d67c41189303aae6425e7835ffdb582814b/src/renderer/entities/governance/lib/opengovThresholdService.ts#L59-L69

I'm having issue verifying whether these functions are correct, and translated correctly. From what I could see, the only way this goes negative, is because `reciprocal.yOffset` is itself negative, this is a constant that is set by the curve.

@stepanLav is now checking with the dev team :pray:

**Comment by Tbaut** [comment]
Do you have any news on this @stepanLav ?
I checked the calculation from Polkassembly, and although there seem to be small differences, such as the use of decision deposit for us, but apparently not for them, the most apparent change between the 2 calculation is that we do a `bnMin(BN_BILLION, <calculated value>)` to get the minimum between the 2 numbers, we end up showing a negative number, whereas they do a `BigNumber.max(<calculated value>, 0)` which will never show a negative number.

https://github.com/polkassembly/polkassembly/blob/fcee134300537ddd180630841ced11178cfd768d/src/components/Post/GovernanceSideBar/Referenda/util.ts#L7-L20

Please let me know if you think I should apply it to us as well.

**Comment by stepanLav** [comment]
@Tbaut 
I asked the Nova team about this and they explained how it works in Nova Wallet:
- When threshold is reached it will be hidden from the user
- When threshold is hidden - will be shown only referenda status (Approve\Reject, etc)

Then I would suggest to do the same in order to avoid case like that, when we may show negative threshold. Some border cases:
- 100 of 1_000_000 -> threshold will be shown
- 100 of 100 -> threshold will be hidden
- 100 of 10 -> threshold will be hidden
- 0 of 0 -> threshold will be hidden
- 0 of -1000 -> threshold will be hidden

**Comment by stepanLav** [comment]
Status verification: ✅
