### ISSUE TITLE
OpenGov. Handle cases when there is no chain account in the wallet

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2075]
Handle cases when there is no account in the wallet for Multishard wallet, Polkadot Vault, WalletConnect, Nova Wallet.

1. [staking](https://www.figma.com/design/JYZVFXo9zdCRDxxcC8pZyD/Update-staking-(2)-%7C-Milestone-3?node-id=677-16183&t=ynE7uPZcD71oAcik-1)
2. [opengov voting](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov-voting?node-id=2758-121589&t=xSUYUeeeU2sjWwAv-1)
3. [opengov delegation](https://www.figma.com/design/4vjREBpvZK7M3m1GaoVptq/OpenGov-delegations?node-id=498-116041&t=ftuF33uxt2i8Ocmp-1)

**Comment by stepanLav** [comment]
Status verification: ✅
