### ISSUE TITLE
OpenGov. Delegations. Add link for adding delegate into the registry

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2086]
1. Add info alert on the delegates list according the [mockup](https://www.figma.com/design/4vjREBpvZK7M3m1GaoVptq/OpenGov-delegations?node-id=328-112932&t=KopjJnJ35FKDIKKk-0)
2. The link `Describe yourself` should lead to [NovaWallet web page](https://docs.novawallet.io/nova-wallet-wiki/opengov/delegate-registry)

**Comment by stepanLav** [comment]
Status verification: ✅
