### ISSUE TITLE
OpenGov. Delegations. Change track names, chips, columns

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2088]
1. Update track info tooltips according [mockups](https://www.figma.com/design/4vjREBpvZK7M3m1GaoVptq/OpenGov-delegations?node-id=616-351163&t=juIhqHXDMhEdwAx1-1)
2. Update input error according [mockups](https://www.figma.com/design/4vjREBpvZK7M3m1GaoVptq/OpenGov-delegations?node-id=1-6616&t=13j78gZNNZhG9peL-0)
3. Update track selection according [mockups](https://www.figma.com/design/4vjREBpvZK7M3m1GaoVptq/OpenGov-delegations?node-id=1-5969&t=4aoNNLx92sLCfFrW-0). Chips should be: Select all, Admin, Governance, Treasury, Fellowship.

**Comment by stepanLav** [comment]
Status verification: ✅

What has been verified:
- Tooltips
https://github.com/novasamatech/nova-spektr/issues/2222
- Errors
- Track selection
