### ISSUE TITLE
OpenGov. Vote. Multisig Approve, Reject

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2121]
OpenGov. Vote. Multisig Approve, Reject

- [x] Approve, Reject screen
- [x] Approve, Reject extrinsic

The list of attributes for the screen is listed in the [doc](https://docs.google.com/document/d/1oB7pX_tgBJJD4YI_pSjIwVmSHb7J1la-njYrNPYDmpc/edit#heading=h.injxpefpjlvp)

**Comment by stepanLav** [comment]
Status verification: ✅
