### ISSUE TITLE
OpenGov. Delegations. Revoke delegation

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2122]
* Add revoke delegation button on delegate screen if delegated already 
* Revoke delegation button on multishard delegation info for single account
* Revoke delegation button on multishard delegation info for multiple selected accounts
* Confirm screen for singleshard
* Confirm screen for multishard
* Update multisig operations
* Update basket operations

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Revoke delegations on Kusama
https://github.com/novasamatech/nova-spektr/issues/2349
- Revoke delegate for different wallets
  - https://github.com/novasamatech/nova-spektr/issues/2331

**Comment by stepanLav** [comment]
Status verification: ✅
