### ISSUE TITLE
Governance. Delegate to all tracks. Wrong track array

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2131]
## Description

When user try to delegate in all tracks it fall down with error:
convictionVoting.BadClass
example block:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-test-network-1.novasamatech.org#/explorer/query/0x58dd271ae8920ad4f1bb6174d206befbe1bdafe4d8bbad6e608b8b2457b18a87

## Steps to Reproduce

1. Go to Governance page
2. Select Delegate case
3. Select all tracks
4. Delegate

## Expected Behavior
Successfully delegate, NovaWallet extrinsic example for delegate to all tracks:
[extrinsic](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-test-network-1.novasamatech.org#/extrinsics/decode/0x6d088400f67ceef1fef1a1419a67a10b7ffa429c41f8ba70f51f2e222606fa2a8edcbd4f01bcf1e0ddef17f9d1c18536595fc49eddb98e331d6a12848e8ec65b03f48e3409f38912fb6722eeaa2a3d2e141802695248181fbc7eaa107b5c723999e0844f8055000c00001002201f010f00006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f011400006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f011500006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f011e00006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f011f00006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f010c00006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f010d00006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f012000006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e80000000000000000000000)
[block](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-test-network-1.novasamatech.org#/explorer/query/0xc0d0526d2a1848f1060ba78593319ae7dc8b9364782c00cef531cab247d077c0)

## Actual Behavior
Error:
[extrinsic](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-test-network-1.novasamatech.org#/extrinsics/decode/0x2d0f8400f67ceef1fef1a1419a67a10b7ffa429c41f8ba70f51f2e222606fa2a8edcbd4f011c35a2bdb4f616860390d6bed970338636ec4ac7dfa8d6b7732aba5e34f6f60ad3204f477d37b6fad1adf15188232e6c14efa28d7b7b07b62db31d35b265ae8075020800001002401f010000006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f010200006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f011400006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f010f00006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f010c00006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f011500006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f010b00006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f010e00006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f010a00006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f011e00006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f011f00006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f012000006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f012100006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f012200006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f010100006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e800000000000000000000001f010d00006adffdaa8e6b18abb296889ccce3c0a9d54aefbad07c386e81e5609b280c9f2a010010a5d4e80000000000000000000000)
[block](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-test-network-1.novasamatech.org#/explorer/query/0x58dd271ae8920ad4f1bb6174d206befbe1bdafe4d8bbad6e608b8b2457b18a87)

## Environment
https://github.com/novasamatech/nova-spektr/commit/b684d4d72c57f1886b1f49125131fafe6db13165

**Comment by pgolovkin** [comment]
Nova Wallet reference 
![telegram-cloud-photo-size-2-5339382542593287585-y](https://github.com/user-attachments/assets/b5bddf91-41f5-4f45-83dc-0e5d72d005dd)

**Comment by stepanLav** [comment]
Problem with model, it takes track list from Polkadot, there is no 2 track id on test network

**Comment by stepanLav** [comment]
Status verification: ✅
