### ISSUE TITLE
OpenGov. Remove vote. Remove vote

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2145]
Remove vote message with link
Remove vote confirm screen

[figma link](https://www.figma.com/design/4vjREBpvZK7M3m1GaoVptq/OpenGov-delegations?node-id=103-67807&t=p1RPRfqc8l6y2SI5-4)

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Remove votes flow

Found during the testing:
- https://github.com/novasamatech/nova-spektr/issues/2216

**Comment by stepanLav** [comment]
Status verification: ✅
