### ISSUE TITLE
OpenGov. Remove vote. Remove vote confirmation screen

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2146]
OpenGov. Remove vote. Remove vote confirmation screen

- [x] show how Governance lock changes
- [ ] show locking period
- [x] show network fee

- [x] Extrinsics ([doc](https://docs.google.com/document/d/1AWNpTQbmfgLMrILjx1n8UClwPattQ1-6mA3n9Geosms/edit#heading=h.uni5bokpvdu5))

Wallets:
- [x] Single Polkadot Vault wallet
- [x] Proxied wallet
- [x] WalletConnect, Nova Wallet wallet
- [ ] Multishard wallet, Polkadot Vault wallet
- [x] Multisig wallet

[Figma mockups](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov-voting?node-id=655-77174&t=NP1elzrHA6b2XQZF-4)

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Regular remove votes
- Proxy remove votes
https://github.com/novasamatech/nova-spektr/issues/2283
- Multisig remove votes
https://github.com/novasamatech/nova-spektr/issues/2284

**Comment by stepanLav** [comment]
Status verification: ✅
