### ISSUE TITLE
Wrong staking modals size

### ISSUE THREAD

**Issue by sokolova-an** [novasamatech/nova-spektr#2163]
## Description
Staking modals don't look correct 

## Screenshots

![Image](https://github.com/user-attachments/assets/30e6b80f-6fc5-4709-91d4-edfdd384919a)

![Image](https://github.com/user-attachments/assets/190f5c3a-f26a-48c3-b1f3-668a09d0a23b)

**Comment by stepanLav** [comment]
Status verification: ✅
