### ISSUE TITLE
Bad signature error when delegating

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2164]
### Expected result
1. Sign delegating transaction
2. Transaction executed successfully

### Actual result
1. Sign delegating transaction
2. Get the error "Transaction has a bad signature"

[bad signature.log](https://github.com/user-attachments/files/16690879/bad.signature.log)
https://github.com/user-attachments/assets/8f37ec38-fc26-45c3-bb28-0bfa5f70b235

**Comment by sokolova-an** [comment]
The same error appears in Staking if you call multiple operations in a row like:
1) sign Stake more;
2) sign Unstake;
3) Sign Change validators - the error usually appears here, on the 3rd steps

**Comment by stepanLav** [comment]
Status verification: ✅
