### ISSUE TITLE
Governance. Can't delegate to another delegate

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2165]
### The scenario
1. Delegate to the 1st delegate
2. Select 2nd delegate
3. Try to delegate

### Expected result
1. Open 2nd delegate
2. Select tracks (that are not already delegated to the 1st delegate and not voted)
3. Sign transaction
4. Transaction executed

### Actual result
1. Open 2nd delegate
2. There is no button for delegate
3. The information about delegation to the 1st delegate is shown 

https://github.com/user-attachments/assets/65f5668e-9425-4690-a41f-cc3dff7b30e4

**Comment by stepanLav** [comment]
Status verification: ❌

Reproduced:
- Delegate to another delegator, while user already has delegations
  - Also there is some problems with delegates state (tracks fetched not after delegate, only after reload)

https://github.com/user-attachments/assets/e4aea724-a071-4ecd-ae14-d844a346e8ea


https://github.com/novasamatech/nova-spektr/commit/cb012730236d518d6ac8c00c662b47397ad0135d

**Comment by stepanLav** [comment]
Status verification: ✅

Found during testing:
https://github.com/novasamatech/nova-spektr/issues/2244
