### ISSUE TITLE
XCM. Migrate to XMC config v6

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2167]
1. Migrate to XCM config V6 changing the [constant](https://github.com/novasamatech/nova-spektr/blob/d4cce2ffc77feaf371e235fa0a2842032a746560/src/renderer/shared/api/xcm/lib/constants.ts#L4) in the code
2. XCM transfers V6 config is located in nova-utils repo https://github.com/novasamatech/nova-utils/tree/master/xcm/v6
3. Update the config in order to use `transfers.json` for production, `trasfers_dev.json` for dev
4. Update the code for new config version if needed

**Comment by pgolovkin** [comment]
Updated the priority for Fellowship release. So that the user may top up collectives account in the Spektr.

**Comment by stepanLav** [comment]
Temp removed Moonbeam \ Moonriver XCMs:
- https://github.com/novasamatech/nova-spektr/issues/2678

need enable it in that issue

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- [Polkadotxcm (Limited_teleport_assets)](https://assethub-polkadot.subscan.io/extrinsic/7832591-2) ❌ (filtered)
Comparison data - [comparison.pdf](https://github.com/user-attachments/files/18227364/comparison.pdf)
compared with [novaWallet's one](https://assethub-polkadot.subscan.io/extrinsic/7832597-2)
- [Xcmpallet (Limited_reserve_transfer_assets)](https://kusama.subscan.io/xcm_message/kusama-a89f80822a42c22be31289a9c57405bd5b2dd8e6) ✅
- [Xtokens (Transfer_multiasset)](https://karura.subscan.io/extrinsic/8268918-2) ❌ (AssetHasNoReserve)
Comparison data - [comparison_2.pdf](https://github.com/user-attachments/files/18227521/comparison_2.pdf)
compared with [novaWallet's one](https://karura.subscan.io/extrinsic/8268922-2)

**Comment by stepanLav** [comment]
Reproduced:
- https://assethub-polkadot.subscan.io/extrinsic/7840797-2

Old with New:
![Image](https://github.com/user-attachments/assets/3ed9d6d4-0ab7-4755-b8c8-429fc7958b74)

New with NovaWallet:
![Image](https://github.com/user-attachments/assets/cd34aaae-7fba-4b6e-beea-651470a1daf4)

**Comment by stepanLav** [comment]
Status verification: ✅
