### ISSUE TITLE
Governance. Can't delegate on Kusama

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2183]
## Description
When user try to delegate on Kusama it stack in loading state.

https://github.com/user-attachments/assets/d83a61e1-dc80-4b9f-be21-e53a43c2d4b2

## Steps to Reproduce

1. Go to Governance page
2. Select Kusama
3. Delegate to all tracks

## Expected Behavior
Successfully submit the operation

## Actual Behavior
Infinity loading state

## Environment
https://github.com/novasamatech/nova-spektr/commit/b3df41c6c90545340866518c64736bcda4d6d21a

**Comment by stepanLav** [comment]
After long time the app have got a status - invalid but it still in submitting state:
<img width="1464" alt="Screenshot 2024-08-22 at 12 48 49" src="https://github.com/user-attachments/assets/e806ce15-2027-4ee0-a1e5-a54c871ea513">

**Comment by Asmadek** [comment]
[android implementation](https://github.com/novasamatech/nova-wallet-android/blob/dcfc1c55faae4cdf3ef750706caac23af5990db6/runtime/src/main/java/io/novafoundation/nova/runtime/extrinsic/multi/ExtrinsicSplitter.kt#L35
)

**Comment by stepanLav** [comment]
Status verification: ✅

- Delegate on Kusama

Found during testing:
- https://github.com/novasamatech/nova-spektr/issues/2262

**Comment by stepanLav** [comment]
Status verification: ✅
