### ISSUE TITLE
Governance. Wrong available amount in Delegation

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2184]
## Description

When user delegate with already locked tokens it shows wrong Available balance (does not include locked balance)
<img width="1464" alt="Screenshot 2024-08-22 at 12 32 41" src="https://github.com/user-attachments/assets/8da589b4-8ea7-4e38-8f53-54dc5477b67c">

## Steps to Reproduce

1. Add locked balance via vote or delegate
2. Go to Add new delegation flow

## Expected Behavior
On confirmation page shows locked balance + transferable in available part

## Actual Behavior
Only transferable balance part is shown

## Environment
https://github.com/novasamatech/nova-spektr/commit/ee67896d8f551b7d6792cb9880528ac7c66e1bb4

**Comment by pgolovkin** [comment]
@sokolova-an  please fix it for voting too.

**Comment by stepanLav** [comment]
Status verification: ✅

Created separate issue to count staking balance:
- https://github.com/novasamatech/nova-spektr/issues/2272
