### ISSUE TITLE
Governance. Proxy. Can't Vote as a proxy if wallet is WalletConnect - empty confirm

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2237]
## Description

Use WalletConnect wallet as a proxy

<img width="600" alt="Screenshot 2024-08-28 at 12 33 26" src="https://github.com/user-attachments/assets/1d2858e0-8d6b-4d36-a042-5101151adaac">

https://github.com/user-attachments/assets/c9b08ab8-0beb-4cc7-ab3a-d42fe18919d1

## Environment
https://github.com/novasamatech/nova-spektr/commit/f0478b0ec6f2c9a4089e196925d183a21f1c4f22

**Comment by stepanLav** [comment]
The same for delegations:

https://github.com/user-attachments/assets/91e4e193-9087-4ab1-8104-3782d725ba34

**Comment by stepanLav** [comment]
Reproduced because of wallet type, that was watch only. It's not a normal state

**Comment by johnthecat** [comment]
Can't reproduce on fresh accounts
