### ISSUE TITLE
OpenGov. Delegations. Delegation summary

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2250]
Add modal with 3 tabs 
* List of delegations
* Voted last 30 days
* Voted for all time list

[figma link](https://www.figma.com/design/4vjREBpvZK7M3m1GaoVptq/OpenGov-delegations?node-id=1-4402&t=p1RPRfqc8l6y2SI5-4)

**Comment by stepanLav** [comment]
Status verification: ❌

- https://github.com/novasamatech/nova-spektr/issues/2369
- https://github.com/novasamatech/nova-spektr/issues/2368

**Comment by stepanLav** [comment]
Status verification: ✅
