### ISSUE TITLE
Governance. Lock. Delegate locks improvement

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2253]
## Description

Need to improve Lock modal window in order to show to whom have been delegated and how much.
Adapt for multishard wallet

## Expected Behavior
https://www.figma.com/design/4vjREBpvZK7M3m1GaoVptq/OpenGov-delegations?node-id=1-5940&t=vZtJhSKe6yvfNUYR-4
![image](https://github.com/user-attachments/assets/77a04b4a-48b3-4394-9e2f-2628343f810a)

## Actual Behavior
<img width="1464" alt="Screenshot 2024-08-29 at 17 26 26" src="https://github.com/user-attachments/assets/b1eb0081-b873-4646-8da3-0712b211a6c5">

## Environment
https://github.com/novasamatech/nova-spektr/commit/36ae481f640b7dcb5a1da20399dd1189bd161718

**Comment by tuul-wq** [comment]
Decided to stick to Nova Wallet pattern - Show "Your delegation" in locks modal and concrete delegation info inside Delegation modal.
