### ISSUE TITLE
Governance. Multisig operations. There is no default message for Vote / Remove Vote

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2290]
## Expected Behavior
?

## Actual Behavior
<img width="747" alt="Screenshot 2024-09-05 at 16 19 47" src="https://github.com/user-attachments/assets/a60c71ab-bb53-4ec1-a707-5110e3cffde1">
<img width="755" alt="Screenshot 2024-09-05 at 16 21 31" src="https://github.com/user-attachments/assets/33f85ce9-159d-4630-a9a6-9f062052a824">

## Environment
https://github.com/novasamatech/nova-spektr/commit/023df867e4ea11596d331f02f572caada4bbeaf6

**Comment by pgolovkin** [comment]
For the transition period (before we implement Multisig without Matrix) the following default Description may be used: `Remove votes for referendum #referendum index`, `Vote for referendum #referendum index`

**Comment by stepanLav** [comment]
Status verification: ✅
