### ISSUE TITLE
Label: added new colors

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2340]
https://www.figma.com/design/uBSPUDFpAkKjYNpA9XTXzh/OpenGov-fellowship?node-id=195-10517&t=KLX7vtrgNXcbI0S7-1

**Comment by stepanLav** [comment]
Status verification: ✅

What has been verified:
- Colour for all ranks

Found problem for colour higher than 7:
https://github.com/novasamatech/nova-spektr/issues/2779
