### ISSUE TITLE
Governance. Delegations. Retract vote on Delegate

### ISSUE THREAD

**Issue by Asmadek** [novasamatech/nova-spektr#2347]
Add message and remove vote button for Select tracks form when have voted tracks . 

[Design](https://www.figma.com/design/4vjREBpvZK7M3m1GaoVptq/OpenGov-delegations?node-id=278-431384&t=QaGQVRuLdvFX2u3O-4)

TODO: #2364

**Comment by stepanLav** [comment]
Status verification: ❌

There is no message on track selection in edit\add new delegation flow:
- https://github.com/novasamatech/nova-spektr/issues/2371

**Comment by stepanLav** [comment]
Status verification: ✅
