### ISSUE TITLE
Avail. Can't calculate fee

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2353]
## Description

<img width="1464" alt="Screenshot 2024-09-19 at 13 38 01" src="https://github.com/user-attachments/assets/c1a05688-4d4d-4911-8139-4335ca5e6a10">

## Environment
https://github.com/novasamatech/nova-spektr/commit/b3a381d4e43fe8ca1218e07e785f903d5eda47a4

**Comment by pgolovkin** [comment]
The following approach has to be used https://github.com/web3alert/substrate-client/commit/23cee277fdea0107b260bcde233574d6b3a30aff#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L22

Telenova Does the same.

**Comment by tuul-wq** [comment]
Created [issue](https://github.com/paritytech/txwrapper-core/issues/411) in txwrapper repo.

**Comment by leohar** [comment]
Status verification: ✅
