### ISSUE TITLE
WalletConnect. Refresh won't update the list of accounts

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2354]
## Description

When user refresh walletconnect wallet it will request old list of accounts.

## Steps to Reproduce

1. Connect to WalletConnect
2. Add new network to the config
3. Refresh wallet 

## Expected Behavior
Wallet connect will be requested with updated network list

## Actual Behavior
Refresh will request old list of networks

## Environment
https://github.com/novasamatech/nova-spektr/commit/b3a381d4e43fe8ca1218e07e785f903d5eda47a4

**Comment by pgolovkin** [comment]
Probably may be fixed with https://github.com/novasamatech/nova-spektr/pull/1255

**Comment by leohar** [comment]
Case:
1. Add account via WC or Nova -> refresh
Actual result:
- after accepting the refresh in Nova it adds second wc session in Nova app
![Image](https://github.com/user-attachments/assets/72c91896-3942-4499-af10-d3a3ff1fcaf0)

Expected result:

**Comment by Asmadek** [comment]
We are use [SignClient.connect](https://specs.walletconnect.com/2.0/specs/clients/sign/client-api) method with pairing topic to update accounts/networks from nova wallet.

But when we try to do it right after initial connection, we receive error `No matching key. pairing topic doesn't exist.`

But after few days everything works fine. (Friday => Monday)

**Comment by stepanLav** [comment]
Reproduced if perform that case:

1. Connect to WalletConnect
2. Switch the internet off
3. Restart the app
4. Return the Intenet
5. Try to reconnect

## Expected result:

Session was updated

## Actual result:

New session was created in the NovaWallet (active session + 1) and error appear in the Spektr:

https://github.com/user-attachments/assets/557afffc-ae9d-4006-b638-d49f0a76ac47


## Additional info
Looks refresh perform in few actions:
- Send event to create new session to NovaWallet
  - Accept connection into NovaWallet
 - Receive event about accept
 - Update data locally
 - Send event to NovaWallet to close the old session

That case happened when we not receive event about accept secon session and keep old session
