### ISSUE TITLE
Governance. Delegate activity. Does not send additional request to subquery

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2358]
## Description
Request to the SubQuery does not send, when user open delegate details.

## Steps to Reproduce

1. Go to Governance
2. Perform Add new delegation case with a new account
3. Check delegation data by opening and closing delegator's detail

## Expected Behavior
Each time, when delegator details opens - send SubQuery request
Or send SubQuery request each block

## Actual Behavior
Will be sent only one request, when click on Delegate button from the Governance page

## Environment
https://github.com/novasamatech/nova-spektr/commit/907ef85d25843ce185820b08897f97ef87d87e49

**Comment by pgolovkin** [comment]
Add a new request when open view.

**Comment by stepanLav** [comment]
Status verification: ✅
