### ISSUE TITLE
Governance. Remove vote from delegation. Support multishard wallets

### ISSUE THREAD

**Issue by Asmadek** [novasamatech/nova-spektr#2364]
Add possibility to remove votes from several accounts in multishard wallet 

[Design](https://www.figma.com/design/4vjREBpvZK7M3m1GaoVptq/OpenGov-delegations?node-id=278-466405&t=rB5DzyOTkADknAKC-4)

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- remove vote window
https://github.com/novasamatech/nova-spektr/issues/2403
- remove vote for a few accounts in multisahrd
https://github.com/novasamatech/nova-spektr/issues/2423#issuecomment-2398923394
- remove votes from the basket
https://github.com/novasamatech/nova-spektr/issues/2425

**Comment by stepanLav** [comment]
Status verification: ✅
