### ISSUE TITLE
OpenGov. Add URL for referendums

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2367]
OpenGov. Add URL for referendums.

Like for transfer there should be the URL with chain and referenda id so that Nova Spektr will be able to open the link by the URL.

![Image](https://github.com/user-attachments/assets/3f5c5dcc-ec70-4012-ac92-f7fdd6227c9f)

**Comment by leohar** [comment]
Status verification: ✅ 

What has been verified:
* open with different params, open from scratch
* negative testing: wrong ref id, absent network id
* maybe we need to have some error processing policy in case ref is not found?
