### ISSUE TITLE
OpenGov. Add timers for referendums

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2375]
Actual result:
1. There are not timers for referendums
2. There are no additional status for referendums (Passing/Wait for deposit)

Expected result:
1. There are timers for referendums according [mockups](https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov-voting?node-id=83-5367&t=ocnBEnOtTNVQDQj6-4)

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- Approve
- Reject
https://github.com/novasamatech/nova-spektr/issues/2393
- Time out
- Referenda details
https://github.com/novasamatech/nova-spektr/issues/2402

**Comment by stepanLav** [comment]
Status verification: ✅
