### ISSUE TITLE
Run indexer for multisig task

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2392]
Run multisig indexer for following networks:

1. Polkadot
2. Kusama
3. Moonbeam
4. Hydration
5. Polkadot asset hub
6. Kusama asset hub
7. Polkadot People Chain
8. Kusama People Chain
9. AlephZero
10. Westend

The `multisig` option has to be changed for chains.json and chains_dev.json

**Comment by stepanLav** [comment]
Add new projects:
- https://github.com/novasamatech/subquery-proxy/pull/16
Deploy:
- https://github.com/novasamatech/infrastructure/pull/158
Update config:
- https://github.com/novasamatech/nova-spektr-utils/pull/179

**Comment by stepanLav** [comment]
Deployed stg and prod env:
https://github.com/novasamatech/infrastructure/tree/main/projects/subquery/proxy
