### ISSUE TITLE
Governance. Delegate summary. Split vote shows as NAY - 0

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2410]
## Description

<img width="1464" alt="Screenshot 2024-10-04 at 13 52 49" src="https://github.com/user-attachments/assets/b65ea296-9c05-497c-a98e-04c66d26f551">

## Steps to Reproduce

1. Find in Kusama - Ce68Nk7s5CD71sXrAvvRQe9uox4jD7ZkTrV8LU81DjTq3ZR delegate
2. Open his details
3. Open Delegate summary

## Expected Behavior
Split state or something
https://www.figma.com/design/4vjREBpvZK7M3m1GaoVptq?node-id=1-4442#974216928

## Actual Behavior
NAY - 0

## Environment
https://github.com/novasamatech/nova-spektr/commit/adf7b6d2214011243ad7025e4d4a0f3af16be80b

**Comment by pgolovkin** [comment]
mockups https://www.figma.com/design/4vjREBpvZK7M3m1GaoVptq/OpenGov-delegations?node-id=1952-342329&t=SHxWWXkhrGLTW3Or-1

**Comment by stepanLav** [comment]
Status verification: ✅
