### ISSUE TITLE
Multisig. Search in create multisig apply to address book

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2485]
## Description

When user search in multisig creation flow, it applies to Address Book

https://github.com/user-attachments/assets/f1d92886-5aaa-46f0-9375-bb50ae2931b0

## Environment
https://github.com/novasamatech/nova-spektr/commit/6ca515af94bd4d44ea25ada390bcc01455cd4bc4

**Comment by Tbaut** [comment]
I'm reusing the `const [contacts, contactsFiltered] = useUnit([contactModel.$contacts, filterModel.$contactsFiltered]);` here so if you happen to have the address book open, then yes the change reflects here too. 

I see several options:
- I create a dedicated model and filter (cons this is 100% duplicated code)
- I manage this in react (cons we do the same, with a different taste)
- this is minor, the chances that users see this is low (they need the address book page open), and it doesn't affect the process in any way, we forget about it.

Can you think about any other solution else @johnthecat ?
I would tend to do either 3 we forget about it, or 2 in React. What should I go for?

**Comment by johnthecat** [comment]
@Tbaut Hi! Of course every user flow should have separate state management. Also we should avoid unnecessary complexity in simple cases.
My personal rule of thumb - if it's sync, simple, and abstract logic, you should avoid additional layer of state management. In this case we already have helper `performSearch` and you can put filtering result into `useMemo` hook.

**Comment by Tbaut** [comment]
Thanks that's helpful, I didn't know about `performSearch`. I implemented it that way in #2543
