### ISSUE TITLE
Multisig. Create multisig. Confirm window. Uses old approach to show info (inside container)

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2488]
## Description

Example:

https://github.com/user-attachments/assets/d47f3e35-88a6-4fbc-8c18-0c9d1f7fbaf9

## Steps to Reproduce

1. Create multisig
2. On confirm screen click on Signatories
3. Try to open details of signatories

## Expected Behavior
Shows above of main container

## Actual Behavior
Opens inside

## Environment
https://github.com/novasamatech/nova-spektr/commit/6ca515af94bd4d44ea25ada390bcc01455cd4bc4

**Comment by Tbaut** [comment]
Can you point me to the component that have the new approach @johnthecat ?
