### ISSUE TITLE
Multisig. Signatories does not match with address book\wallets

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2495]
## Description

If user add someone to Address Book, there is no changes in Multisig signatories.

Example:

https://github.com/user-attachments/assets/59be5d6f-1caa-40d5-a7c9-091766fa0ed2

## Steps to Reproduce

1. Add to Address book someone from your signatories list in one of the Multisigs
2. Open Multisig details again

## Expected Behavior
Shows name and address from Address Book

## Actual Behavior
There is no changes

## Environment
https://github.com/novasamatech/nova-spektr/commit/6ca515af94bd4d44ea25ada390bcc01455cd4bc4

**Comment by stepanLav** [comment]
Also, in "Your accounts" section are shown addresses, without link to particular wallet\account:

<img width="1464" alt="Screenshot 2024-10-17 at 12 32 22" src="https://github.com/user-attachments/assets/ce3f0bb5-a048-41b7-92bc-5aed45433230">

**Comment by Tbaut** [comment]
While this is a perfectly valid annoyance, I'd like to point out that this must have always been the case and is not specifically related to my changes since I did not modify any code in this area of the app.

**Comment by leohar** [comment]
Status verification: ✅
