### ISSUE TITLE
Govenrnace. Multishard wallet with only one account in network has wrong flow.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2496]
## Description

When user has multishard wallet with only one account in network, on Delegate page is available - "Add new delegation", which is wrong, should be available only Edit

![IMAGE 2024-10-17 14:17:22](https://github.com/user-attachments/assets/5404bd30-2b97-4b1b-8921-aa6f4eb99cae)

## Steps to Reproduce

1. Add multishard wallet with only one account in the network
2. Delegate to someone from this account
3. Open Delegate details

## Expected Behavior
Available only Edit flow

## Actual Behavior
Add new delegation is available, but there is no way to add new delegation, as account is already delegated.

## Environment
https://github.com/novasamatech/nova-spektr/commit/ea2d06b9832a6570cbc59e8ba6197989603407c4

**Comment by pgolovkin** [comment]
Should be researched in order to make an abstraction for operations.
