### ISSUE TITLE
The app stay in the background after closing, can't reopen

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2503]
## Description

When user close the app by cross button in interface, the app still work in background and can't be run another instance of application

example:

https://github.com/user-attachments/assets/f728763a-74cd-4476-988f-9ed961a61306

## Environment
Release v1.11.0

Also reproduced on the dev - https://github.com/novasamatech/nova-spektr/commit/ea2d06b9832a6570cbc59e8ba6197989603407c4

**Comment by pgolovkin** [comment]
Steps:
1. build prod from dev
2. try to run and reproduce the problem

**Comment by pgolovkin** [comment]
@johnthecat reproduced on Mac M1. `Renderer` process is stopped when the window is closed. When I reopen the app `Renderer` process doesn't start.

**Comment by stepanLav** [comment]
Status verification: ✅
