### ISSUE TITLE
Multisig. Can't properly interact with address field in multisig creation flow

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2508]
## Description

Address field is opened inside another container and crop from each side.

Example:

https://github.com/user-attachments/assets/df3809a8-14ef-48e0-88e9-c2f1b1ddb034

## Environment
https://github.com/novasamatech/nova-spektr/commit/0a3e32d5edae91d623fe09e5f930055e615e403a

**Comment by leohar** [comment]
Status verification: ✅
