### ISSUE TITLE
Multisig. Can process with the same signatories.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2510]
## Description

When user creates multisig it should not allow to add the same addresses multiple times

Example:

https://github.com/user-attachments/assets/516f08c3-1856-4c03-be0d-2cd2fec54fb3

## Steps to Reproduce

1. Go to Multisig creation flow
2. On "Create multisig" window add a few signatories with the same addresses

## Expected Behavior
Unique account list in signatory participations

## Actual Behavior
Can add the same address multiple times

## Environment
https://github.com/novasamatech/nova-spektr/commit/0a3e32d5edae91d623fe09e5f930055e615e403a

**Comment by leohar** [comment]
Status verification: ✅
