### ISSUE TITLE
Multisig. Can create without threshold.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2511]
## Description

User can create multisig wallet without threshold

Example:

https://github.com/user-attachments/assets/dda9e95d-f557-43aa-8fc7-6eebeac31894

## Steps to Reproduce

1. Go to Multisig creation flow
2. Add creator account
3. Add signatories
4. Press Continue button

## Expected Behavior
Can't proceed with empty threshold, show error

## Actual Behavior
Can proceed

## Environment
https://github.com/novasamatech/nova-spektr/commit/0a3e32d5edae91d623fe09e5f930055e615e403a

**Comment by leohar** [comment]
Status verification: ✅
- can not create without threshold
- can create with => 2
