### ISSUE TITLE
Flexible multisig. Refactor confirm screens

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2541]
For easier adoption of new wallet type we decided to move accounts/wallets block in confirm screens to generic implementation.
Draft of this implementation called [`TransactionDetails`](https://spektr-storybook.s3-website.nl-ams.scw.cloud/?path=/docs/design-system-entities-transactiondetails--docs). There are few screens that are not follow this pattern, they should keep unchanged.

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:
- multisig operations
https://github.com/novasamatech/nova-spektr/issues/2594
- transfers

**Comment by stepanLav** [comment]
Status verification: ✅
