### ISSUE TITLE
Multisig. Operations screen doesn't reload the data

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2567]
**The scenario**
The user 1:
1. opens operations page

The user 2:
1. Creates or signs multisig operation

**Expected result**
1. The user 1 sees update operation page with multisig operation

**Actual result**
1. The user 1 doesn't see updated operations page until operation page revisit

DOD:
1. Fix autoupdate of operations page

**Comment by stepanLav** [comment]
Status verification: ✅
