### ISSUE TITLE
Multisig. On account import switches to discovered multisig

### ISSUE THREAD

**Issue by leohar** [novasamatech/nova-spektr#2570]
## Description
Can catch empty or broken state on adding account when switching to ms wallet on import

## Steps to Reproduce

1. Go to Wallet management - add any account, which is member of ms via NW: `136uvBV9iWwEUMxyApcFy3Y79JD4oSdKwyzMsFxmdkELzUm5`

## Actual Behavior
discovers multisig account and switches to it
![Image](https://github.com/user-attachments/assets/9e4199f4-a317-4e9c-b26c-cddba0b40332)
## Expected Behavior
discover multisig, remain on selected account

**Comment by Tbaut** [comment]
This is happening here, the `walletProviderModel.events.completed` is called, which then triggers the navigation.
I should ideally not be called if the user is not in the multisig creation flow.

https://github.com/novasamatech/nova-spektr/blob/6b516abe9bfb0f12d4d5d897910d66f505637078/src/renderer/widgets/CreateWallet/model/flow-model.ts#L263-L266

**Comment by stepanLav** [comment]
Reproduced on https://github.com/novasamatech/nova-spektr/commit/9761c24c9fc3b3e4612dc41a53c44680cff488c5
added as a duplicate occasionally:

https://github.com/novasamatech/nova-spektr/issues/2597

**Comment by stepanLav** [comment]
Status verification: ✅
