### ISSUE TITLE
Multisig. No deposit and fee validation on Confirm

### ISSUE THREAD

**Issue by leohar** [novasamatech/nova-spektr#2580]
## Description
account with amount not available for deposit and fee
## Steps to Reproduce

1. Create multisig -> follow the whole flow -> create ms

## Actual Behavior
allows signing, fails with unavailable fee error

## Expected 
https://www.figma.com/design/HgFuj8QZd0xqEbkG10DIfs/Flexible-multisig-%7C-Milestone-4?node-id=1108-55991&t=0VoLOig1LjxypsJw-1

**Comment by pgolovkin** [comment]
The validation error should be shown on the confirmation screen.

**Comment by stepanLav** [comment]
depends on:
https://github.com/novasamatech/nova-spektr/issues/2615

**Comment by stepanLav** [comment]
Status verification: ✅
