### ISSUE TITLE
Multisig. Can't reject operation via proxy

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2595]
## Description

When user has a proxy for multisig's signatory, reject operation can't be signed.

https://github.com/user-attachments/assets/e0814bf9-f8db-429b-861c-5bd2f43ad594

Account setup:
- [accounts.json](https://github.com/user-attachments/files/17674289/accounts.json)
- [wallets.json](https://github.com/user-attachments/files/17674290/wallets.json)

## Steps to Reproduce

1. Add account_A
2. Create proxy from account_B to account_A
3. Create multisig with account_A\account_B\account_C
4. Create an operation from account_B via account_A using proxy
5. Go to multisig operations
6. Try to reject the operation

## Expected Behavior
Successfully reject the operation via proxy

## Actual Behavior
Can't reject an operation - empty signing page

## Environment
https://github.com/novasamatech/nova-spektr/commit/9761c24c9fc3b3e4612dc41a53c44680cff488c5

**Comment by pgolovkin** [comment]
@sokolova-an it's a duplication for https://github.com/novasamatech/nova-spektr/issues/1774
So please close both bugs when fix.

**Comment by stepanLav** [comment]
Status verification: ⏳

What has been verified:

- https://github.com/novasamatech/nova-spektr/issues/2643
