### ISSUE TITLE
Multisig. Accounts disappear for single chain multisig, created before

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2596]
## Description

When we remove multisig flag from config for some networks - old created single chain multisigs shows 0 network

## Steps to Reproduce

1. Create single multisig for any chain, for example Nova Testnet
2. Remove multisig flag for that network
3. Open multisig details

## Expected Behavior
Shows network for which multisig was created

## Actual Behavior
Shows 0 

<img width="1136" alt="Screenshot 2024-11-08 at 09 08 17" src="https://github.com/user-attachments/assets/6a9cbb9a-2b7f-4d32-908b-0b7a2cb81e49">

<img width="1136" alt="Screenshot 2024-11-08 at 09 31 13" src="https://github.com/user-attachments/assets/c33bc00c-896d-4ec0-8876-053434cb1362">

## Environment
https://github.com/novasamatech/nova-spektr/commit/9761c24c9fc3b3e4612dc41a53c44680cff488c5

**Comment by pgolovkin** [comment]
Accounts must not be filtered out by chains.json.

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Old multisig contains networks for which it was created ✅
- When select those multisigs - network should be available on portfolio view ❌

https://github.com/user-attachments/assets/97c545b2-3674-47ac-9b0c-270c8f76f253

Moved to separate task - https://github.com/novasamatech/nova-spektr/issues/2656

**Comment by stepanLav** [comment]
Status verification: ✅
