### ISSUE TITLE
Multisig. Create new multisig - does not depend which signatory do you select, will be used the first one

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2613]
## Description

https://github.com/user-attachments/assets/4c168ccd-b8ce-42db-8a1c-0b157aaf1e45

## Steps to Reproduce

1. Add the same wallet via different wallet types (wc\polkadot vault)
2. Go to multisig creation
3. Select signatory as a wallet
4. Try to create wallet
5. Select second signatory to sign

## Expected Behavior
Can switch between signatories and wallet types

## Actual Behavior
Can't select which signing type will be used, always first is used

## Environment
https://github.com/novasamatech/nova-spektr/commit/1b29836ffc7ca408a44df236bae6f0d8b98bf087

**Comment by pgolovkin** [comment]
Should be clarified with https://github.com/novasamatech/nova-spektr/issues/2581

**Comment by stepanLav** [comment]
Status verification: ✅
