### ISSUE TITLE
Wallet management. Move wallets CRUD into one model.

### ISSUE THREAD

**Issue by johnthecat** [novasamatech/nova-spektr#2631]
There are a lot of places, where wallet list got mutated. It produces a lot of unexpected bugs and collisions  between features.
To address this problem we should move all wallet operations into wallet model and give simple API for modifying wallets list without touching it directly.

**Comment by johnthecat** [comment]
Affected area:
* adding each type of wallet
* modifying wallets in every possible way (rename, shards edit, etc.)
* editing proxy and pure proxy
* wallet selection

**Comment by stepanLav** [comment]
Status verification: ✅

What has been verified:
- Adding all wallets types (onboarding\additional wallet)
- modifying wallets in every possible way (rename, shards edit, etc.)
- add \ delete proxies
- select different wallets
