### ISSUE TITLE
Multisig. Old multisig wallets become unusable

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2656]
## Description

Portfolio view contains no chains for single Multisig wallets, which was removed from config

https://github.com/user-attachments/assets/97c545b2-3674-47ac-9b0c-270c8f76f253

## Scenario:
1. Add multisig to any chain
2. Remove multisig flag for this chain in config
3. Restart the app

## Expected results:
Old multisigs should work

## Actual result:
Portfolio view is empty

## Environment
https://github.com/novasamatech/nova-spektr/commit/993f059a3cee32a9324eb293a40652e4ca3b07cc

**Comment by pgolovkin** [comment]
This should be fixed for the release.

On the balances page the filtering must be improved. If the network doesn't have multisig option but exists in the wallet accounts list then show the balance for it.
