### ISSUE TITLE
Multisig. Address book. Auto adding new rows works wrong

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2662]
## Description

Auto adding to address book works wrong:
- signatories without name will save
- new rows will appear only after app will be restarted

Example:

https://github.com/user-attachments/assets/5eeb22b6-61de-40bf-9434-d5e502e563fb

## Steps to Reproduce

1. Go to Multisig creation flow
2. Add signatory without the name
3. Create multisig

## Expected Behavior
Signatory will be added to address book:
- if name was assigned to the signatory, otherwise it won't
- new contact appear on Address book page

## Actual Behavior
1. Signatory will be transfered to contact even if the name was not specified
2. Address book page will be updated only after restart the app

## Environment
https://github.com/novasamatech/nova-spektr/commit/52ace73fbd72dd015680c620e9e3dfbaa53e67a5

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Create new multisig wallet will add new signatory in Address book ✅
- Won't create contact in address book if name for signatory was not provided ❌ 

https://github.com/user-attachments/assets/b3ae2753-98ff-4dd9-a7bb-c571001ea3e2

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- When user use signatory without name it shouldn't create a new contact

Example:

https://github.com/user-attachments/assets/a609ad44-0150-4699-bf6e-b81b5b3a6aaa

**Comment by Asmadek** [comment]
Update requirements: Show error empty signatory name

**Comment by stepanLav** [comment]
Status verification: ✅
