### ISSUE TITLE
XCM. Moonbeam \ Moonreaver - can't calculate fee

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2678]
## Description

Can't calculate fee for Moonriver\Moonbeam XCMs

Error:
```
Error getting fee -  TypeError: Cannot read properties of undefined (reading 'transferMultiasset')
```

https://github.com/user-attachments/assets/278957ec-558a-4b13-b6a6-5221f699ad3a

## Environment
PROD

**Comment by pgolovkin** [comment]
NovaWallet fix https://github.com/novasamatech/nova-utils/pull/3186

**Comment by pgolovkin** [comment]
@stepanLav as we discussed:
1. Short-term fix - turn off broken XCM transfer for the upcoming release
2. Fix it with XCM V6 support

**Comment by stepanLav** [comment]
Removed in that PR:
https://github.com/novasamatech/nova-utils/pull/3197

**Comment by stepanLav** [comment]
Status verification: ✅
