### ISSUE TITLE
OpenGov. Improve referendum URL UX

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2743]
Update referenda URL:
1. Default chain must be Polkadot. If chain is not specified in URL then Polkadot must be used by default
2. For chain the chain name from chains.json may be used. The example is `/polkadot/<referenda_id>`

**Comment by stepanLav** [comment]
Status verification: ✅

What has been verified:
- Default chain is Polkadot
- For all Referenda the chain name were taken
- Old url format
