### ISSUE TITLE
Portfolio. Update UI

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2752]
Update UI in order to align it with Nova Wallet. Mockups [link](https://www.figma.com/design/n8IgGoYgK0HT1zWDF5uNYy/Portfolio-view-%7C-Milestone-4?node-id=585-25199&t=gJMj8NGGEpBXR3R1-4)
1. Move networks to the left ![Image](https://github.com/user-attachments/assets/5184a4d5-81f7-47f8-84a1-4b8405d00b28)
2. If token allocated in 3 networks show logo of 3 networks but not `+1` ![Image](https://github.com/user-attachments/assets/b8c60ba2-084a-42b8-ace4-511331a904e7)
3. Network icon should be in the subtitle ![Image](https://github.com/user-attachments/assets/8b1b863d-5a64-43ea-92da-2f5d16962dc3)
4. Show token icon (network icon is in the subtitle - item 3) ![Image](https://github.com/user-attachments/assets/fff2f40e-0b24-404a-96ef-d4a13b92193c)
5. Update `салфетка` UI: Animation and look&feel. [Prototype](https://www.figma.com/proto/n8IgGoYgK0HT1zWDF5uNYy/Portfolio-view-%7C-Milestone-4?page-id=569%3A20380&node-id=593-48500&node-type=frame&viewport=6197%2C-6535%2C1.34&t=tnytM3KAIl9GCV72-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=613%3A23151).

**Comment by pgolovkin** [comment]
@tuul-wq updated prototype [link](https://www.figma.com/proto/n8IgGoYgK0HT1zWDF5uNYy/Portfolio-view-%7C-Milestone-4?page-id=569%3A20380&node-id=593-48500&node-type=frame&viewport=6197%2C-6535%2C1.34&t=tnytM3KAIl9GCV72-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=613%3A23151)

**Comment by pgolovkin** [comment]
@tuul-wq please make item 6 - update according the design review - [link](https://www.figma.com/design/eqaw6XqIm2Ox8nQ2QpUN36/Design-review?node-id=375-3475&t=lFeOPLLG1PEgDgWF-4)

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Asset icon ✅
- Network icon ✅
- Roll down \ roll up animation ✅
- Updated counter ❌
  - https://github.com/novasamatech/nova-spektr/issues/2792

**Comment by stepanLav** [comment]
Status verification: ✅
