### ISSUE TITLE
Portfolio view. Update according the design-review

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2764]
Update portfolio view according the design review - [link](https://www.figma.com/design/eqaw6XqIm2Ox8nQ2QpUN36/Design-review?node-id=375-3475&t=lFeOPLLG1PEgDgWF-4)

**Comment by stepanLav** [comment]
Status verification: ⏳

Checked:
- State 1 ✅
- State 2 ✅
- State 3 ❌
  - https://github.com/novasamatech/nova-spektr/issues/2793
- State 4 ✅
- State 5 ❌
  - https://github.com/novasamatech/nova-spektr/issues/2794
- State 6 ✅
- State 7 - need clarification

**Comment by stepanLav** [comment]
Status verification: ✅
