### ISSUE TITLE
Portfolio view. Token balance doesn't match sum of token balances in networks

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2770]
Token balance doesn't match sum of token balances in networks.

![Image](https://github.com/user-attachments/assets/35cfc479-687d-42e8-8e62-aa1cbf4bc889)

**Comment by stepanLav** [comment]
Reproduced in electron:

https://github.com/user-attachments/assets/c7ea8a00-b6fc-49bc-89e1-dd45d1171163

**Comment by stepanLav** [comment]
Status verification: ✅
