### ISSUE TITLE
Fellowship. 8 Rank looks white, as 0

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2779]
## Description

<img width="600" alt="Screenshot 2024-12-04 at 20 19 33" src="https://github.com/user-attachments/assets/e0ff69c7-9f13-46d9-abba-e3c7b9223943">

## Expected Behavior

Colour scheme for rank higher than 7

## Actual Behavior

Color as for 0

## Environment
https://github.com/novasamatech/nova-spektr/commit/9566874b5af6958a8708dcdb05794b3622ac25db

**Comment by pgolovkin** [comment]
Now days the max rank in collectives that member has if 7. 
But in 6 months it may be changed.
However the max rank is 9. 

So ranks 8, 9 has to be supported.


![Image](https://github.com/user-attachments/assets/3636a45c-4a0a-4b7f-a1b1-5c05842129c2)
![Image](https://github.com/user-attachments/assets/3b7fa3dc-13b1-4d2f-b74d-9db6c203b9da)

**Comment by pgolovkin** [comment]
@johnthecat Rank was updated in mockups, please check that mockups match implementation https://www.figma.com/design/uBSPUDFpAkKjYNpA9XTXzh/OpenGov-fellowship?t=BUKWOMQjQgvqJvRC-0

**Comment by stepanLav** [comment]
Status verification: ✅
