### ISSUE TITLE
XCM. Fee verification needs to be updated

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2833]
## Description

Currently we do not check cross-chain fee in Available balance when make XCMs

**Expected result:**
Show error - "Insufficient balance to pay cross-chain fee"
Would be better to make it more responsive and show which exact token insufficiently and on which account

## Environment
https://github.com/novasamatech/nova-spektr/commit/e94c6422fbca2e2d6007d819d5a7f33919213bc8

**Comment by pgolovkin** [comment]
The rest will be fixed with https://github.com/novasamatech/nova-spektr/issues/2851
