### ISSUE TITLE
Multisig. Can't decode multisig batch (batchAll) operation with unknown extrinsics

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2900]
Multisig. Can't decode multisig batch (batchAll) operation with unknown extrinsics.

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Create operation from polkadot.js app
Unknown operation state

![Image](https://github.com/user-attachments/assets/b53a475b-90be-43e2-a935-ecec783feea0)


operation - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-test-network-1.novasama-tech.org#/explorer/query/0xccdc67e0af1324ddeb79edd8f96028d13924b391c48045265c0a98129395bd8b

Test Data:
[multisigTransactions.json](https://github.com/user-attachments/files/18374107/multisigTransactions.json)
[wallets.json](https://github.com/user-attachments/files/18374108/wallets.json)
[accounts.json](https://github.com/user-attachments/files/18374109/accounts.json)

**Comment by stepanLav** [comment]
Status verification: ❌

What has been verified:
- Parse batchAll multisig operation

![Image](https://github.com/user-attachments/assets/6a096a28-df4a-4c62-8455-e24fec36a3fd)

Expected result:
Parse as batchall

Actual result:
Parsed as first operation in transactions list

Test data:

[spektr-database.json](https://github.com/user-attachments/files/18451320/spektr-database.json)
