### ISSUE TITLE
OpenGov. Undelegate period seems incorrect

### ISSUE THREAD

**Issue by pgolovkin** [novasamatech/nova-spektr#2918]
Undelegation period is not reducing, it has to be shown (like unstaking period)<img width="455" alt="Image" src="https://github.com/user-attachments/assets/711251c3-52b9-43c7-93b6-8e6e815134b5" />

**Comment by Jason-Tariq** [comment]
Hello @pgolovkin  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
